
@prefix ns: <http://ontology.universaal.org/PhThing.owl#> .
@prefix ns1: <urn:org.universAAL.aal_space:test_environment#> .
@prefix ns2: <http://ontology.universAAL.org/UI.owl#> .
@prefix pvn: <http://ontology.universAAL.org/uAAL.owl#> .
@prefix ns3: <http://ontology.universAAL.org/Language.owl#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix ns4: <http://ontology.universAAL.org/Profile.owl#> .
@prefix ns5: <http://ui.universAAL.org/dmFileStorage.owl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix ns6: <http://ontology.universaal.org/InteractionPreferencesProfile.owl#> .
@prefix ns7: <urn:org.universAAL.safety:test_environment#> .
@prefix ns8: <http://ontology.universaal.org/language.owl#> .
@prefix : <http://ontology.universAAL.org/Dialog.owl#> .
_:BN000000 ns5:suspended [
      ns6:interactionPreferences ns1:saiedSubprofileUIPreferencesGeneralInteractionPreferences ;
      ns2:altPresentationModality pvn:voice ;
      ns6:visualPreferences ns1:saiedSubprofileUIPreferencesVisualPreferences ;
      ns2:dialogLanguage "en"^^xsd:language ;
      ns2:presentationModality pvn:gui ;
      a ns2:UIRequest ;
      ns2:dialogForm <http://ontology.universAAL.org/Dialog.owl#_:a0283ced120a689a:1911> ;
      ns2:dialogPrivacyLevel pvn:insensible ;
      ns6:audioPreferences ns1:saiedSubprofileUIPreferencesAuditoryPreferences ;
      ns6:alertPreferences ns1:saiedSubprofileUIPreferencesAlertPreferences ;
      ns2:addressedUser ns1:saied ;
      ns6:accessMode ns1:saiedSubprofileUIPreferencesAccessMode ;
      ns2:dialogPriority pvn:high
    ] ,
    [
      ns6:interactionPreferences ns1:saiedSubprofileUIPreferencesGeneralInteractionPreferences ;
      ns2:altPresentationModality pvn:voice ;
      ns6:visualPreferences ns1:saiedSubprofileUIPreferencesVisualPreferences ;
      ns2:dialogLanguage "en"^^xsd:language ;
      ns2:presentationModality pvn:gui ;
      a ns2:UIRequest ;
      ns2:dialogForm <http://ontology.universAAL.org/Dialog.owl#_:a0283ced344fcf99:15da> ;
      ns2:dialogPrivacyLevel pvn:insensible ;
      ns6:audioPreferences ns1:saiedSubprofileUIPreferencesAuditoryPreferences ;
      ns6:alertPreferences ns1:saiedSubprofileUIPreferencesAlertPreferences ;
      ns2:addressedUser ns1:saied ;
      ns6:accessMode ns1:saiedSubprofileUIPreferencesAccessMode ;
      ns2:dialogPriority pvn:high
    ] ,
    [
      ns6:interactionPreferences ns1:saiedSubprofileUIPreferencesGeneralInteractionPreferences ;
      ns2:altPresentationModality pvn:voice ;
      ns6:visualPreferences ns1:saiedSubprofileUIPreferencesVisualPreferences ;
      ns2:dialogLanguage "en"^^xsd:language ;
      ns2:presentationModality pvn:gui ;
      a ns2:UIRequest ;
      ns2:dialogForm <http://ontology.universAAL.org/Dialog.owl#_:a0283ced36028ef4:1a00> ;
      ns2:dialogPrivacyLevel pvn:insensible ;
      ns6:audioPreferences ns1:saiedSubprofileUIPreferencesAuditoryPreferences ;
      ns6:alertPreferences ns1:saiedSubprofileUIPreferencesAlertPreferences ;
      ns2:addressedUser ns1:saied ;
      ns6:accessMode ns1:saiedSubprofileUIPreferencesAccessMode ;
      ns2:dialogPriority pvn:middle
    ] ,
    [
      ns6:interactionPreferences ns1:saiedSubprofileUIPreferencesGeneralInteractionPreferences ;
      ns2:altPresentationModality pvn:voice ;
      ns6:visualPreferences ns1:saiedSubprofileUIPreferencesVisualPreferences ;
      ns2:dialogLanguage "en"^^xsd:language ;
      ns2:presentationModality pvn:gui ;
      a ns2:UIRequest ;
      ns2:dialogForm <http://ontology.universAAL.org/Dialog.owl#_:a0283ced64a4159b:1623> ;
      ns2:dialogPrivacyLevel pvn:insensible ;
      ns6:audioPreferences ns1:saiedSubprofileUIPreferencesAuditoryPreferences ;
      ns6:alertPreferences ns1:saiedSubprofileUIPreferencesAlertPreferences ;
      ns2:addressedUser ns7:saied ;
      ns6:accessMode ns1:saiedSubprofileUIPreferencesAccessMode ;
      ns2:dialogPriority pvn:middle
    ] ,
    [
      ns6:interactionPreferences ns1:saiedSubprofileUIPreferencesGeneralInteractionPreferences ;
      ns2:altPresentationModality pvn:voice ;
      ns6:visualPreferences ns1:saiedSubprofileUIPreferencesVisualPreferences ;
      ns2:dialogLanguage "en"^^xsd:language ;
      ns2:presentationModality pvn:gui ;
      a ns2:UIRequest ;
      ns2:dialogForm <http://ontology.universAAL.org/Dialog.owl#_:a0283ced6e2d5d98:155b> ;
      ns2:dialogPrivacyLevel pvn:insensible ;
      ns6:audioPreferences ns1:saiedSubprofileUIPreferencesAuditoryPreferences ;
      ns6:alertPreferences ns1:saiedSubprofileUIPreferencesAlertPreferences ;
      ns2:addressedUser ns1:saied ;
      ns6:accessMode ns1:saiedSubprofileUIPreferencesAccessMode ;
      ns2:dialogPriority pvn:high
    ] ,
    [
      ns6:interactionPreferences ns1:saiedSubprofileUIPreferencesGeneralInteractionPreferences ;
      ns2:altPresentationModality pvn:voice ;
      ns6:visualPreferences ns1:saiedSubprofileUIPreferencesVisualPreferences ;
      ns2:dialogLanguage "en"^^xsd:language ;
      ns2:presentationModality pvn:gui ;
      a ns2:UIRequest ;
      ns2:dialogForm <http://ontology.universAAL.org/Dialog.owl#_:a0283ced878a1a82:1862> ;
      ns2:dialogPrivacyLevel pvn:insensible ;
      ns6:audioPreferences ns1:saiedSubprofileUIPreferencesAuditoryPreferences ;
      ns6:alertPreferences ns1:saiedSubprofileUIPreferencesAlertPreferences ;
      ns2:addressedUser ns1:saied ;
      ns6:accessMode ns1:saiedSubprofileUIPreferencesAccessMode ;
      ns2:dialogPriority pvn:middle
    ] ,
    [
      ns6:interactionPreferences ns7:saiedSubprofileUIPreferencesGeneralInteractionPreferences ;
      ns2:altPresentationModality pvn:voice ;
      ns6:visualPreferences ns7:saiedSubprofileUIPreferencesVisualPreferences ;
      ns2:dialogLanguage "en"^^xsd:language ;
      ns2:presentationModality pvn:gui ;
      a ns2:UIRequest ;
      ns2:dialogPrivacyLevel pvn:insensible ;
      ns2:dialogForm <http://ontology.universAAL.org/Dialog.owl#_:a0283cedac41bf30:18bf> ;
      ns6:audioPreferences ns7:saiedSubprofileUIPreferencesAuditoryPreferences ;
      ns6:alertPreferences ns7:saiedSubprofileUIPreferencesAlertPreferences ;
      ns2:addressedUser ns7:saied ;
      ns2:dialogPriority pvn:middle ;
      ns6:accessMode ns7:saiedSubprofileUIPreferencesAccessMode
    ] ,
    [
      ns6:interactionPreferences ns7:saiedSubprofileUIPreferencesGeneralInteractionPreferences ;
      ns2:altPresentationModality pvn:voice ;
      ns6:visualPreferences ns7:saiedSubprofileUIPreferencesVisualPreferences ;
      ns2:dialogLanguage "en"^^xsd:language ;
      ns2:presentationModality pvn:gui ;
      a ns2:UIRequest ;
      ns2:dialogForm <http://ontology.universAAL.org/Dialog.owl#_:a0283cedac8934a:13e5> ;
      ns2:dialogPrivacyLevel pvn:insensible ;
      ns6:audioPreferences ns7:saiedSubprofileUIPreferencesAuditoryPreferences ;
      ns6:alertPreferences ns7:saiedSubprofileUIPreferencesAlertPreferences ;
      ns2:addressedUser ns7:saied ;
      ns2:dialogPriority pvn:middle ;
      ns6:accessMode ns7:saiedSubprofileUIPreferencesAccessMode
    ] ,
    [
      ns6:interactionPreferences ns7:saiedSubprofileUIPreferencesGeneralInteractionPreferences ;
      ns2:altPresentationModality pvn:voice ;
      ns6:visualPreferences ns7:saiedSubprofileUIPreferencesVisualPreferences ;
      ns2:dialogLanguage "en"^^xsd:language ;
      ns2:presentationModality pvn:gui ;
      a ns2:UIRequest ;
      ns2:dialogForm <http://ontology.universAAL.org/Dialog.owl#_:a0283cedf5b165c5:1477> ;
      ns2:dialogPrivacyLevel pvn:insensible ;
      ns6:audioPreferences ns7:saiedSubprofileUIPreferencesAuditoryPreferences ;
      ns6:alertPreferences ns7:saiedSubprofileUIPreferencesAlertPreferences ;
      ns2:addressedUser ns7:saied ;
      ns2:dialogPriority pvn:middle ;
      ns6:accessMode ns7:saiedSubprofileUIPreferencesAccessMode
    ] ,
    [
      ns6:interactionPreferences ns7:saiedSubprofileUIPreferencesGeneralInteractionPreferences ;
      ns2:altPresentationModality pvn:voice ;
      ns6:visualPreferences ns7:saiedSubprofileUIPreferencesVisualPreferences ;
      ns2:dialogLanguage "en"^^xsd:language ;
      ns2:presentationModality pvn:gui ;
      a ns2:UIRequest ;
      ns2:dialogForm <http://ontology.universAAL.org/Dialog.owl#_:a0283cedf5b165c5:1488> ;
      ns2:dialogPrivacyLevel pvn:insensible ;
      ns6:audioPreferences ns7:saiedSubprofileUIPreferencesAuditoryPreferences ;
      ns6:alertPreferences ns7:saiedSubprofileUIPreferencesAlertPreferences ;
      ns2:addressedUser ns7:saied ;
      ns2:dialogPriority pvn:middle ;
      ns6:accessMode ns7:saiedSubprofileUIPreferencesAccessMode
    ] ,
    [
      ns6:interactionPreferences ns7:saiedSubprofileUIPreferencesGeneralInteractionPreferences ;
      ns2:altPresentationModality pvn:voice ;
      ns6:visualPreferences ns7:saiedSubprofileUIPreferencesVisualPreferences ;
      ns2:dialogLanguage "en"^^xsd:language ;
      ns2:presentationModality pvn:gui ;
      a ns2:UIRequest ;
      ns2:dialogForm <http://ontology.universAAL.org/Dialog.owl#_:a0283cedf5b165c5:1793> ;
      ns2:dialogPrivacyLevel pvn:insensible ;
      ns6:audioPreferences ns7:saiedSubprofileUIPreferencesAuditoryPreferences ;
      ns6:alertPreferences ns7:saiedSubprofileUIPreferencesAlertPreferences ;
      ns2:addressedUser ns7:saied ;
      ns2:dialogPriority pvn:middle ;
      ns6:accessMode ns7:saiedSubprofileUIPreferencesAccessMode
    ] ;
  ns5:active [
      ns6:interactionPreferences ns1:saiedSubprofileUIPreferencesGeneralInteractionPreferences ;
      ns2:altPresentationModality pvn:voice ;
      ns6:visualPreferences ns1:saiedSubprofileUIPreferencesVisualPreferences ;
      ns2:dialogLanguage "en"^^xsd:language ;
      ns2:presentationModality pvn:gui ;
      a ns2:UIRequest ;
      ns2:dialogForm <http://ontology.universAAL.org/Dialog.owl#_:a0283ced6e2d5d98:15d4> ;
      ns2:dialogPrivacyLevel pvn:insensible ;
      ns6:audioPreferences ns1:saiedSubprofileUIPreferencesAuditoryPreferences ;
      ns6:alertPreferences ns1:saiedSubprofileUIPreferencesAlertPreferences ;
      ns2:addressedUser ns1:saied ;
      ns6:accessMode ns1:saiedSubprofileUIPreferencesAccessMode ;
      ns2:dialogPriority pvn:high
    ] ,
    [
      ns6:interactionPreferences ns1:saiedSubprofileUIPreferencesGeneralInteractionPreferences ;
      ns2:altPresentationModality pvn:voice ;
      ns6:visualPreferences ns1:saiedSubprofileUIPreferencesVisualPreferences ;
      ns2:dialogLanguage "en"^^xsd:language ;
      ns2:presentationModality pvn:gui ;
      a ns2:UIRequest ;
      ns2:dialogForm <http://ontology.universAAL.org/Dialog.owl#_:a0283ced344fcf99:1664> ;
      ns2:dialogPrivacyLevel pvn:insensible ;
      ns6:audioPreferences ns1:saiedSubprofileUIPreferencesAuditoryPreferences ;
      ns6:alertPreferences ns1:saiedSubprofileUIPreferencesAlertPreferences ;
      ns2:addressedUser ns1:saied ;
      ns6:accessMode ns1:saiedSubprofileUIPreferencesAccessMode ;
      ns2:dialogPriority pvn:high
    ] ,
    [
      ns6:interactionPreferences ns7:saiedSubprofileUIPreferencesGeneralInteractionPreferences ;
      ns2:altPresentationModality pvn:voice ;
      ns6:visualPreferences ns7:saiedSubprofileUIPreferencesVisualPreferences ;
      ns2:dialogLanguage "en"^^xsd:language ;
      ns2:presentationModality pvn:gui ;
      a ns2:UIRequest ;
      ns2:dialogPrivacyLevel pvn:insensible ;
      ns2:dialogForm <http://ontology.universAAL.org/Dialog.owl#_:a0283ced64a4159b:1632> ;
      ns6:audioPreferences ns7:saiedSubprofileUIPreferencesAuditoryPreferences ;
      ns6:alertPreferences ns7:saiedSubprofileUIPreferencesAlertPreferences ;
      ns2:addressedUser ns7:saied ;
      ns2:dialogPriority pvn:middle ;
      ns6:accessMode ns7:saiedSubprofileUIPreferencesAccessMode
    ] ,
    [
      ns6:interactionPreferences ns7:saiedSubprofileUIPreferencesGeneralInteractionPreferences ;
      ns2:altPresentationModality pvn:voice ;
      ns6:visualPreferences ns7:saiedSubprofileUIPreferencesVisualPreferences ;
      ns2:dialogLanguage "en"^^xsd:language ;
      ns2:presentationModality pvn:gui ;
      a ns2:UIRequest ;
      ns2:dialogForm <http://ontology.universAAL.org/Dialog.owl#_:a0283cedac41bf30:1923> ;
      ns2:dialogPrivacyLevel pvn:insensible ;
      ns6:audioPreferences ns7:saiedSubprofileUIPreferencesAuditoryPreferences ;
      ns6:alertPreferences ns7:saiedSubprofileUIPreferencesAlertPreferences ;
      ns2:addressedUser ns7:saied ;
      ns2:dialogPriority pvn:middle ;
      ns6:accessMode ns7:saiedSubprofileUIPreferencesAccessMode
    ] ,
    [
      ns6:interactionPreferences ns7:saiedSubprofileUIPreferencesGeneralInteractionPreferences ;
      ns2:altPresentationModality pvn:voice ;
      ns6:visualPreferences ns7:saiedSubprofileUIPreferencesVisualPreferences ;
      ns2:dialogLanguage "en"^^xsd:language ;
      ns2:presentationModality pvn:gui ;
      a ns2:UIRequest ;
      ns2:dialogForm <http://ontology.universAAL.org/Dialog.owl#_:a0283cedac41bf30:22f2> ;
      ns2:dialogPrivacyLevel pvn:insensible ;
      ns6:audioPreferences ns7:saiedSubprofileUIPreferencesAuditoryPreferences ;
      ns6:alertPreferences ns7:saiedSubprofileUIPreferencesAlertPreferences ;
      ns2:addressedUser ns7:saied ;
      ns2:dialogPriority pvn:middle ;
      ns6:accessMode ns7:saiedSubprofileUIPreferencesAccessMode
    ] ,
    [
      ns6:interactionPreferences ns1:saiedSubprofileUIPreferencesGeneralInteractionPreferences ;
      ns2:altPresentationModality pvn:voice ;
      ns6:visualPreferences ns1:saiedSubprofileUIPreferencesVisualPreferences ;
      ns2:dialogLanguage "en"^^xsd:language ;
      ns2:presentationModality pvn:gui ;
      a ns2:UIRequest ;
      ns2:dialogForm <http://ontology.universAAL.org/Dialog.owl#_:a0283ced53b25bb2:196a> ;
      ns2:dialogPrivacyLevel pvn:insensible ;
      ns6:audioPreferences ns1:saiedSubprofileUIPreferencesAuditoryPreferences ;
      ns6:alertPreferences ns1:saiedSubprofileUIPreferencesAlertPreferences ;
      ns2:addressedUser ns1:saied ;
      ns6:accessMode ns1:saiedSubprofileUIPreferencesAccessMode ;
      ns2:dialogPriority pvn:middle
    ] ,
    [
      ns6:interactionPreferences ns1:saiedSubprofileUIPreferencesGeneralInteractionPreferences ;
      ns2:altPresentationModality pvn:voice ;
      ns6:visualPreferences ns1:saiedSubprofileUIPreferencesVisualPreferences ;
      ns2:dialogLanguage "en"^^xsd:language ;
      ns2:presentationModality pvn:gui ;
      a ns2:UIRequest ;
      ns2:dialogForm <http://ontology.universAAL.org/Dialog.owl#_:a0283ced53b25bb2:19ad> ;
      ns2:dialogPrivacyLevel pvn:insensible ;
      ns6:audioPreferences ns1:saiedSubprofileUIPreferencesAuditoryPreferences ;
      ns6:alertPreferences ns1:saiedSubprofileUIPreferencesAlertPreferences ;
      ns2:addressedUser ns1:saied ;
      ns6:accessMode ns1:saiedSubprofileUIPreferencesAccessMode ;
      ns2:dialogPriority pvn:middle
    ] ,
    [
      ns6:interactionPreferences ns1:saiedSubprofileUIPreferencesGeneralInteractionPreferences ;
      ns2:altPresentationModality pvn:voice ;
      ns6:visualPreferences ns1:saiedSubprofileUIPreferencesVisualPreferences ;
      ns2:dialogLanguage "en"^^xsd:language ;
      ns2:presentationModality pvn:gui ;
      a ns2:UIRequest ;
      ns2:dialogForm <http://ontology.universAAL.org/Dialog.owl#_:a0283ced53b25bb2:19bc> ;
      ns2:dialogPrivacyLevel pvn:insensible ;
      ns6:audioPreferences ns1:saiedSubprofileUIPreferencesAuditoryPreferences ;
      ns6:alertPreferences ns1:saiedSubprofileUIPreferencesAlertPreferences ;
      ns2:addressedUser ns1:saied ;
      ns6:accessMode ns1:saiedSubprofileUIPreferencesAccessMode ;
      ns2:dialogPriority pvn:middle
    ] ,
    [
      ns6:interactionPreferences ns1:saiedSubprofileUIPreferencesGeneralInteractionPreferences ;
      ns2:altPresentationModality pvn:voice ;
      ns6:visualPreferences ns1:saiedSubprofileUIPreferencesVisualPreferences ;
      ns2:dialogLanguage "en"^^xsd:language ;
      ns2:presentationModality pvn:gui ;
      a ns2:UIRequest ;
      ns2:dialogForm <http://ontology.universAAL.org/Dialog.owl#_:a0283ced36028ef4:1a0f> ;
      ns2:dialogPrivacyLevel pvn:insensible ;
      ns6:audioPreferences ns1:saiedSubprofileUIPreferencesAuditoryPreferences ;
      ns6:alertPreferences ns1:saiedSubprofileUIPreferencesAlertPreferences ;
      ns2:addressedUser ns1:saied ;
      ns6:accessMode ns1:saiedSubprofileUIPreferencesAccessMode ;
      ns2:dialogPriority pvn:middle
    ] ,
    [
      ns6:interactionPreferences ns1:saiedSubprofileUIPreferencesGeneralInteractionPreferences ;
      ns2:altPresentationModality pvn:voice ;
      ns6:visualPreferences ns1:saiedSubprofileUIPreferencesVisualPreferences ;
      ns2:dialogLanguage "en"^^xsd:language ;
      ns2:presentationModality pvn:gui ;
      a ns2:UIRequest ;
      ns2:dialogForm <http://ontology.universAAL.org/Dialog.owl#_:a0283ced36028ef4:1a1f> ;
      ns2:dialogPrivacyLevel pvn:insensible ;
      ns6:audioPreferences ns1:saiedSubprofileUIPreferencesAuditoryPreferences ;
      ns6:alertPreferences ns1:saiedSubprofileUIPreferencesAlertPreferences ;
      ns2:addressedUser ns1:saied ;
      ns6:accessMode ns1:saiedSubprofileUIPreferencesAccessMode ;
      ns2:dialogPriority pvn:middle
    ] ,
    [
      ns6:interactionPreferences ns1:saiedSubprofileUIPreferencesGeneralInteractionPreferences ;
      ns2:altPresentationModality pvn:voice ;
      ns6:visualPreferences ns1:saiedSubprofileUIPreferencesVisualPreferences ;
      ns2:dialogLanguage "en"^^xsd:language ;
      ns2:presentationModality pvn:gui ;
      a ns2:UIRequest ;
      ns2:dialogForm <http://ontology.universAAL.org/Dialog.owl#_:a0283ced878a1a82:18e1> ;
      ns2:dialogPrivacyLevel pvn:insensible ;
      ns6:audioPreferences ns1:saiedSubprofileUIPreferencesAuditoryPreferences ;
      ns6:alertPreferences ns1:saiedSubprofileUIPreferencesAlertPreferences ;
      ns2:addressedUser ns1:saied ;
      ns6:accessMode ns1:saiedSubprofileUIPreferencesAccessMode ;
      ns2:dialogPriority pvn:middle
    ] ,
    [
      ns6:interactionPreferences ns1:saiedSubprofileUIPreferencesGeneralInteractionPreferences ;
      ns2:altPresentationModality pvn:voice ;
      ns6:visualPreferences ns1:saiedSubprofileUIPreferencesVisualPreferences ;
      ns2:dialogLanguage "en"^^xsd:language ;
      ns2:presentationModality pvn:gui ;
      a ns2:UIRequest ;
      ns2:dialogForm <http://ontology.universAAL.org/Dialog.owl#_:a0283ced878a1a82:18f0> ;
      ns2:dialogPrivacyLevel pvn:insensible ;
      ns6:audioPreferences ns1:saiedSubprofileUIPreferencesAuditoryPreferences ;
      ns6:alertPreferences ns1:saiedSubprofileUIPreferencesAlertPreferences ;
      ns2:addressedUser ns1:saied ;
      ns6:accessMode ns1:saiedSubprofileUIPreferencesAccessMode ;
      ns2:dialogPriority pvn:middle
    ] ,
    [
      ns6:interactionPreferences ns1:saiedSubprofileUIPreferencesGeneralInteractionPreferences ;
      ns2:altPresentationModality pvn:voice ;
      ns6:visualPreferences ns1:saiedSubprofileUIPreferencesVisualPreferences ;
      ns2:dialogLanguage "en"^^xsd:language ;
      ns2:presentationModality pvn:gui ;
      a ns2:UIRequest ;
      ns2:dialogForm <http://ontology.universAAL.org/Dialog.owl#_:a0283ced878a1a82:18ff> ;
      ns2:dialogPrivacyLevel pvn:insensible ;
      ns6:audioPreferences ns1:saiedSubprofileUIPreferencesAuditoryPreferences ;
      ns6:alertPreferences ns1:saiedSubprofileUIPreferencesAlertPreferences ;
      ns2:addressedUser ns1:saied ;
      ns6:accessMode ns1:saiedSubprofileUIPreferencesAccessMode ;
      ns2:dialogPriority pvn:middle
    ] .
_:BN000052 :groupChildren [
      :parentControl _:BN000052 ;
      :theContent "Lights are on"^^xsd:string ;
      a :SimpleOutput
    ] ,
    [
      :parentControl _:BN000052 ;
      :contentURL "bundle://97.0:1/images/light_on.png"^^xsd:string ;
      a :MediaObject ;
      :contentType "image/png"^^xsd:string ;
      :controlLabel [
        a :Label ;
        rdfs:label ""^^xsd:string
      ]
    ] ;
  :parentControl _:BN000049 ;
  a :Group ;
  :controlLabel [
    a :Label ;
    rdfs:label "ioControlsGroup"^^xsd:string
  ] .
_:BN000053 :groupChildren [
      :parentControl _:BN000053 ;
      :theContent "Lights are on"^^xsd:string ;
      a :SimpleOutput
    ] ,
    [
      :parentControl _:BN000053 ;
      :contentURL "bundle://88.0:1/images/light_on.png"^^xsd:string ;
      a :MediaObject ;
      :contentType "image/png"^^xsd:string ;
      :controlLabel [
        a :Label ;
        rdfs:label ""^^xsd:string
      ]
    ] ;
  :parentControl _:BN000037 ;
  a :Group ;
  :controlLabel [
    a :Label ;
    rdfs:label "ioControlsGroup"^^xsd:string
  ] .
_:BN000054 a :Label ;
  rdfs:label "Delete"^^xsd:string .
_:BN000055 a :Label ;
  rdfs:label "Preserve"^^xsd:string .
_:BN000056 :groupChildren [
      :parentControl _:BN000056 ;
      pvn:submissionID "deleteMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN00001a
    ] ,
    [
      :parentControl _:BN000056 ;
      pvn:submissionID "preserveMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN000043
    ] ;
  :parentControl _:BN000050 ;
  a :Group ;
  :controlLabel [
    a :Label ;
    rdfs:label "submitsGroup"^^xsd:string
  ] .
ns1:saied a ns4:User ,
    ns:PhysicalThing .
_:BN000057 :groupChildren [
      :parentControl _:BN000057 ;
      pvn:submissionID "deleteMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN00003f
    ] ,
    [
      :parentControl _:BN000057 ;
      pvn:submissionID "preserveMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN00001d
    ] ;
  :parentControl _:BN00000c ;
  a :Group ;
  :controlLabel [
    a :Label ;
    rdfs:label "submitsGroup"^^xsd:string
  ] .
_:BN000058 :groupChildren [
      :parentControl _:BN000058 ;
      pvn:submissionID "deleteMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN000054
    ] ,
    [
      :parentControl _:BN000058 ;
      pvn:submissionID "preserveMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN000042
    ] ;
  :parentControl _:BN000015 ;
  a :Group ;
  :controlLabel [
    a :Label ;
    rdfs:label "submitsGroup"^^xsd:string
  ] .
pvn:gui a pvn:Modality .
ns1:saiedSubprofileUIPreferencesGeneralInteractionPreferences ns6:secondaryLanguage ns8:greek ;
  ns6:secondaryModality pvn:voice ;
  a ns6:GeneralInteractionPreferences ;
  ns6:contentDensity ns6:detailed ;
  ns6:preferredLanguage ns8:greek ;
  ns6:preferredModality pvn:gui .
ns8:greek ns3:englishLabel "Greek, Modern"^^xsd:string ;
  a ns3:Greek ;
  ns3:iso639code "el"^^xsd:string ;
  ns3:nativeLabel "ελληνικά"^^xsd:string .
<http://ontology.universAAL.org/Dialog.owl#_:a0283ced120a689a:1911> :creationTimestamp "2013-09-25T13:36:25.549+03:00"^^xsd:dateTime ;
  :dialogType pvn:message ;
  a :Form ;
  :dialogDataRoot [] ;
  :rootGroup _:BN000009 .
ns7:saiedSubprofileUIPreferencesAccessMode ns6:auditoryModeStatus ns6:on ;
  ns6:olfactoryModeStatus ns6:off ;
  a ns6:AccessMode ;
  ns6:textualModeStatus ns6:on ;
  ns6:tactileModeStatus ns6:off ;
  ns6:visualModeStatus ns6:on .
ns7:saiedSubprofileUIPreferencesVisualPreferences ns6:fontColor ns6:black ;
  ns6:componentSpacing ns6:medium ;
  ns6:highlightColor ns6:white ;
  ns6:screenSaverUsage ns6:off ;
  ns6:dayNightMode ns6:on ;
  ns6:screenResolution ns6:medium ;
  a ns6:VisualPreferences ;
  ns6:contentContrast ns6:high ;
  ns6:flashingResources ns6:on ;
  ns6:backgroundColor ns6:lightBlue ;
  ns6:fontFamily ns6:serif ;
  ns6:brightness ns6:medium ;
  ns6:windowLayout ns6:overlap .
<http://ontology.universAAL.org/Dialog.owl#_:a0283ced53b25bb2:19bc> :creationTimestamp "2013-09-25T11:20:54.920+03:00"^^xsd:dateTime ;
  :dialogType pvn:message ;
  a :Form ;
  :dialogDataRoot [] ;
  :rootGroup _:BN000026 .
<http://ontology.universAAL.org/Dialog.owl#_:a0283ced53b25bb2:19ad> :creationTimestamp "2013-09-25T11:20:49.920+03:00"^^xsd:dateTime ;
  :dialogType pvn:message ;
  a :Form ;
  :dialogDataRoot [] ;
  :rootGroup _:BN00000a .
<http://ontology.universAAL.org/Dialog.owl#_:a0283ced6e2d5d98:155b> :creationTimestamp "2013-09-24T17:15:13.097+03:00"^^xsd:dateTime ;
  :dialogType pvn:message ;
  a :Form ;
  :dialogDataRoot [] ;
  :rootGroup _:BN00001f .
ns7:saiedSubprofileUIPreferencesAuditoryPreferences a ns6:AuditoryPreferences ;
  ns6:pitch ns6:medium ;
  ns6:keySound ns6:off ;
  ns6:volume ns6:medium ;
  ns6:systemSounds ns6:on ;
  ns6:speechRate ns6:medium ;
  ns6:voiceGender ns6:female .
<http://ontology.universAAL.org/Dialog.owl#_:a0283cedac41bf30:1923> :creationTimestamp "2013-09-05T14:22:19.942+03:00"^^xsd:dateTime ;
  :dialogType pvn:message ;
  a :Form ;
  :dialogDataRoot [] ;
  :rootGroup _:BN000038 .
ns6:lightBlue a ns6:ColorType .
<http://ontology.universAAL.org/Dialog.owl#_:a0283cedf5b165c5:1488> :creationTimestamp "2013-07-26T15:30:04.665+03:00"^^xsd:dateTime ;
  :dialogType pvn:message ;
  a :Form ;
  :dialogDataRoot [] ;
  :rootGroup _:BN00002c .
<http://ontology.universAAL.org/Dialog.owl#_:a0283ced344fcf99:15da> :creationTimestamp "2013-09-24T17:46:47.759+03:00"^^xsd:dateTime ;
  :dialogType pvn:message ;
  a :Form ;
  :dialogDataRoot [] ;
  :rootGroup _:BN000015 .
ns1:saiedSubprofileUIPreferencesVisualPreferences ns6:fontColor ns6:black ;
  ns6:componentSpacing ns6:medium ;
  ns6:highlightColor ns6:white ;
  ns6:screenSaverUsage ns6:off ;
  ns6:dayNightMode ns6:on ;
  ns6:screenResolution ns6:medium ;
  a ns6:VisualPreferences ;
  ns6:contentContrast ns6:high ;
  ns6:flashingResources ns6:on ;
  ns6:backgroundColor ns6:lightBlue ;
  ns6:fontFamily ns6:serif ;
  ns6:brightness ns6:medium ;
  ns6:windowLayout ns6:overlap .
<http://ontology.universAAL.org/Dialog.owl#_:a0283cedf5b165c5:1477> :creationTimestamp "2013-07-26T15:30:00.702+03:00"^^xsd:dateTime ;
  :dialogType pvn:message ;
  a :Form ;
  :dialogDataRoot [] ;
  :rootGroup _:BN00000d .
ns6:serif a ns6:GenericFontFamily .
ns6:female a ns6:VoiceGender .
ns6:medium a ns6:Intensity .
pvn:middle a pvn:LevelRating .
ns6:overlap a ns6:WindowLayoutType .
_:BN000001 :groupChildren [
      :parentControl _:BN000001 ;
      pvn:submissionID "deleteMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel [
        a :Label ;
        rdfs:label "Delete"^^xsd:string
      ]
    ] ,
    [
      :parentControl _:BN000001 ;
      pvn:submissionID "preserveMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel [
        a :Label ;
        rdfs:label "Preserve"^^xsd:string
      ]
    ] ;
  a :Group ;
  :parentControl _:BN000009 ;
  :controlLabel [
    a :Label ;
    rdfs:label "submitsGroup"^^xsd:string
  ] .
<http://ontology.universAAL.org/Dialog.owl#_:a0283ced6e2d5d98:15d4> :creationTimestamp "2013-09-24T17:19:21.091+03:00"^^xsd:dateTime ;
  :dialogType pvn:message ;
  a :Form ;
  :dialogDataRoot [] ;
  :rootGroup _:BN000050 .
<http://ontology.universAAL.org/Dialog.owl#_:a0283ced878a1a82:18ff> :creationTimestamp "2013-09-25T13:22:15.817+03:00"^^xsd:dateTime ;
  :dialogType pvn:message ;
  a :Form ;
  :dialogDataRoot [] ;
  :rootGroup _:BN000020 .
ns7:saied a ns4:User ,
    ns:PhysicalThing .
<http://ontology.universAAL.org/Dialog.owl#_:a0283cedac8934a:13e5> :creationTimestamp "2013-09-03T14:23:43.671+03:00"^^xsd:dateTime ;
  :dialogType pvn:message ;
  a :Form ;
  :dialogDataRoot [] ;
  :rootGroup _:BN000047 .
ns1:saiedSubprofileUIPreferencesAuditoryPreferences a ns6:AuditoryPreferences ;
  ns6:pitch ns6:medium ;
  ns6:keySound ns6:off ;
  ns6:volume ns6:medium ;
  ns6:systemSounds ns6:on ;
  ns6:speechRate ns6:medium ;
  ns6:voiceGender ns6:female .
_:BN000002 :groupChildren [
      :parentControl _:BN000002 ;
      :theContent "Window is oopen"^^xsd:string ;
      a :SimpleOutput
    ] ,
    [
      :parentControl _:BN000002 ;
      :contentURL "http://127.0.0.1:8080/resources/safety/images/opened_window_s.png"^^xsd:string ;
      a :MediaObject ;
      :contentType "image/png"^^xsd:string ;
      :controlLabel [
        a :Label ;
        rdfs:label "Window"^^xsd:string
      ]
    ] ;
  a :Group ;
  :parentControl _:BN000015 ;
  :controlLabel [
    a :Label ;
    rdfs:label "ioControlsGroup"^^xsd:string
  ] .
_:BN000003 :groupChildren _:BN000011 ,
    _:BN000010 ;
  a :Group ;
  :parentControl <http://ontology.universAAL.org/Dialog.owl#_:a0283ced36028ef4:1a0f> ;
  :controlLabel [
    a :Label ;
    rdfs:label "Door Alert Message"^^xsd:string
  ] .
<http://ontology.universAAL.org/Dialog.owl#_:a0283ced878a1a82:1862> :creationTimestamp "2013-09-25T13:21:53.895+03:00"^^xsd:dateTime ;
  :dialogType pvn:message ;
  a :Form ;
  :dialogDataRoot [] ;
  :rootGroup _:BN000012 .
_:BN000004 :groupChildren [
      :parentControl _:BN000004 ;
      pvn:submissionID "deleteMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN000029
    ] ,
    [
      :parentControl _:BN000004 ;
      pvn:submissionID "preserveMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN000055
    ] ;
  :parentControl _:BN00000d ;
  a :Group ;
  :controlLabel [
    a :Label ;
    rdfs:label "submitsGroup"^^xsd:string
  ] .
_:BN000005 :groupChildren [
      :parentControl _:BN000005 ;
      pvn:submissionID "deleteMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN00004b
    ] ,
    [
      :parentControl _:BN000005 ;
      pvn:submissionID "preserveMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN000023
    ] ;
  a :Group ;
  :parentControl _:BN000032 ;
  :controlLabel [
    a :Label ;
    rdfs:label "submitsGroup"^^xsd:string
  ] .
ns1:saiedSubprofileUIPreferencesAccessMode ns6:auditoryModeStatus ns6:on ;
  ns6:olfactoryModeStatus ns6:off ;
  a ns6:AccessMode ;
  ns6:tactileModeStatus ns6:off ;
  ns6:textualModeStatus ns6:on ;
  ns6:visualModeStatus ns6:on .
_:BN000006 :groupChildren [
      :parentControl _:BN000006 ;
      pvn:submissionID "deleteMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN00002b
    ] ,
    [
      :parentControl _:BN000006 ;
      pvn:submissionID "preserveMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN000018
    ] ;
  :parentControl _:BN00000a ;
  a :Group ;
  :controlLabel [
    a :Label ;
    rdfs:label "submitsGroup"^^xsd:string
  ] .
pvn:high a pvn:LevelRating .
_:BN000007 :groupChildren [
      :parentControl _:BN000007 ;
      :theContent "Lights are oon"^^xsd:string ;
      a :SimpleOutput
    ] ,
    [
      :parentControl _:BN000007 ;
      :contentURL "http://127.0.0.1:8080/resources/safety/images/light_on_s.png"^^xsd:string ;
      a :MediaObject ;
      :contentType "image/png"^^xsd:string ;
      :controlLabel [
        a :Label ;
        rdfs:label "Lights"^^xsd:string
      ]
    ] ;
  a :Group ;
  :parentControl _:BN000050 ;
  :controlLabel [
    a :Label ;
    rdfs:label "ioControlsGroup"^^xsd:string
  ] .
_:BN000008 :groupChildren [
      :parentControl _:BN000008 ;
      :theContent "Lights are on"^^xsd:string ;
      a :SimpleOutput
    ] ,
    [
      :parentControl _:BN000008 ;
      :contentURL "http://127.0.0.1:8080/resources/safety/images/light_on_s.png"^^xsd:string ;
      a :MediaObject ;
      :contentType "image/png"^^xsd:string ;
      :controlLabel [
        a :Label ;
        rdfs:label "Lights"^^xsd:string
      ]
    ] ;
  a :Group ;
  :parentControl _:BN000009 ;
  :controlLabel [
    a :Label ;
    rdfs:label "ioControlsGroup"^^xsd:string
  ] .
_:BN000009 :groupChildren _:BN000001 ,
    _:BN000008 ;
  a :Group ;
  :parentControl <http://ontology.universAAL.org/Dialog.owl#_:a0283ced120a689a:1911> ;
  :controlLabel [
    a :Label ;
    rdfs:label "Lights Alert Message"^^xsd:string
  ] .
_:BN00000a :groupChildren _:BN00000b ,
    _:BN000006 ;
  a :Group ;
  :parentControl <http://ontology.universAAL.org/Dialog.owl#_:a0283ced53b25bb2:19ad> ;
  :controlLabel [
    a :Label ;
    rdfs:label "Door Alert Message"^^xsd:string
  ] .
ns6:white a ns6:ColorType .
_:BN00000b :groupChildren [
      :parentControl _:BN00000b ;
      :theContent "Door is open"^^xsd:string ;
      a :SimpleOutput
    ] ,
    [
      :parentControl _:BN00000b ;
      :contentURL "http://127.0.0.1:8080/resources/safety/images/door_open.png"^^xsd:string ;
      a :MediaObject ;
      :contentType "image/png"^^xsd:string ;
      :controlLabel [
        a :Label ;
        rdfs:label "Door"^^xsd:string
      ]
    ] ;
  :parentControl _:BN00000a ;
  a :Group ;
  :controlLabel [
    a :Label ;
    rdfs:label "ioControlsGroup"^^xsd:string
  ] .
_:BN00000c :groupChildren _:BN000057 ,
    _:BN00001b ;
  a :Group ;
  :parentControl <http://ontology.universAAL.org/Dialog.owl#_:a0283ced64a4159b:1623> ;
  :controlLabel [
    a :Label ;
    rdfs:label "Window Alert Message"^^xsd:string
  ] .
_:BN00000d :groupChildren _:BN000004 ,
    _:BN000031 ;
  a :Group ;
  :parentControl <http://ontology.universAAL.org/Dialog.owl#_:a0283cedf5b165c5:1477> ;
  :controlLabel [
    a :Label ;
    rdfs:label "Window Alert Message"^^xsd:string
  ] .
<http://ontology.universAAL.org/Dialog.owl#_:a0283ced344fcf99:1664> :creationTimestamp "2013-09-24T17:47:13.179+03:00"^^xsd:dateTime ;
  :dialogType pvn:message ;
  a :Form ;
  :dialogDataRoot [] ;
  :rootGroup _:BN000033 .
_:BN00000e :groupChildren [
      :parentControl _:BN00000e ;
      pvn:submissionID "deleteMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN00004f
    ] ,
    [
      :parentControl _:BN00000e ;
      pvn:submissionID "preserveMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN00004d
    ] ;
  a :Group ;
  :parentControl _:BN000045 ;
  :controlLabel [
    a :Label ;
    rdfs:label "submitsGroup"^^xsd:string
  ] .
_:BN00000f :groupChildren [
      :parentControl _:BN00000f ;
      :theContent "Door is open"^^xsd:string ;
      a :SimpleOutput
    ] ,
    [
      :parentControl _:BN00000f ;
      :contentURL "http://127.0.0.1:8080/resources/safety/images/door_open.png"^^xsd:string ;
      a :MediaObject ;
      :contentType "image/png"^^xsd:string ;
      :controlLabel [
        a :Label ;
        rdfs:label "Door"^^xsd:string
      ]
    ] ;
  a :Group ;
  :parentControl _:BN000045 ;
  :controlLabel [
    a :Label ;
    rdfs:label "ioControlsGroup"^^xsd:string
  ] .
_:BN000010 :groupChildren [
      :parentControl _:BN000010 ;
      pvn:submissionID "deleteMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN00004f
    ] ,
    [
      :parentControl _:BN000010 ;
      pvn:submissionID "preserveMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN00004d
    ] ;
  a :Group ;
  :parentControl _:BN000003 ;
  :controlLabel [
    a :Label ;
    rdfs:label "submitsGroup"^^xsd:string
  ] .
_:BN000011 :groupChildren [
      :parentControl _:BN000011 ;
      :theContent "Door is open"^^xsd:string ;
      a :SimpleOutput
    ] ,
    [
      :parentControl _:BN000011 ;
      :contentURL "http://127.0.0.1:8080/resources/safety/images/door_open.png"^^xsd:string ;
      a :MediaObject ;
      :contentType "image/png"^^xsd:string ;
      :controlLabel [
        a :Label ;
        rdfs:label "Door"^^xsd:string
      ]
    ] ;
  a :Group ;
  :parentControl _:BN000003 ;
  :controlLabel [
    a :Label ;
    rdfs:label "ioControlsGroup"^^xsd:string
  ] .
_:BN000012 :groupChildren _:BN000016 ,
    _:BN000021 ;
  a :Group ;
  :parentControl <http://ontology.universAAL.org/Dialog.owl#_:a0283ced878a1a82:1862> ;
  :controlLabel [
    a :Label ;
    rdfs:label "Visitor Alert Message"^^xsd:string
  ] .
_:BN000013 :groupChildren [
      :parentControl _:BN000013 ;
      pvn:submissionID "deleteMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN000014
    ] ,
    [
      :parentControl _:BN000013 ;
      pvn:submissionID "preserveMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN000019
    ] ;
  a :Group ;
  :parentControl _:BN00002e ;
  :controlLabel [
    a :Label ;
    rdfs:label "submitsGroup"^^xsd:string
  ] .
_:BN000014 a :Label ;
  rdfs:label "Delete"^^xsd:string .
_:BN000015 :groupChildren _:BN000058 ,
    _:BN000002 ;
  a :Group ;
  :parentControl <http://ontology.universAAL.org/Dialog.owl#_:a0283ced344fcf99:15da> ;
  :controlLabel [
    a :Label ;
    rdfs:label "New Window Alert Message"^^xsd:string
  ] .
_:BN000016 :groupChildren [
      :parentControl _:BN000016 ;
      pvn:submissionID "deleteMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN000014
    ] ,
    [
      :parentControl _:BN000016 ;
      pvn:submissionID "preserveMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN000019
    ] ;
  :parentControl _:BN000012 ;
  a :Group ;
  :controlLabel [
    a :Label ;
    rdfs:label "submitsGroup"^^xsd:string
  ] .
ns6:on a ns6:Status .
_:BN000017 :groupChildren [
      :parentControl _:BN000017 ;
      :theContent "Unknown Person is knocking on the door."^^xsd:string ;
      a :SimpleOutput
    ] ,
    [
      :parentControl _:BN000017 ;
      :contentURL "http://127.0.0.1:8080/resources/safety/images/Unknown_Person.png"^^xsd:string ;
      a :MediaObject ;
      :contentType "image/png"^^xsd:string ;
      :controlLabel [
        a :Label ;
        rdfs:label ""^^xsd:string
      ]
    ] ;
  a :Group ;
  :parentControl _:BN000028 ;
  :controlLabel [
    a :Label ;
    rdfs:label "ioControlsGroup"^^xsd:string
  ] .
_:BN000018 a :Label ;
  rdfs:label "Preserve"^^xsd:string .
<http://ontology.universAAL.org/Dialog.owl#_:a0283cedf5b165c5:1793> :creationTimestamp "2013-07-26T15:33:42.786+03:00"^^xsd:dateTime ;
  :dialogType pvn:message ;
  a :Form ;
  :dialogDataRoot [] ;
  :rootGroup _:BN000037 .
_:BN000019 a :Label ;
  rdfs:label "Preserve"^^xsd:string .
<http://ontology.universAAL.org/Dialog.owl#_:a0283ced53b25bb2:196a> :creationTimestamp "2013-09-25T11:20:44.932+03:00"^^xsd:dateTime ;
  :dialogType pvn:message ;
  a :Form ;
  :dialogDataRoot [] ;
  :rootGroup _:BN00003a .
_:BN00001a a :Label ;
  rdfs:label "Delete"^^xsd:string .
<http://ontology.universAAL.org/Dialog.owl#_:a0283ced878a1a82:18f0> :creationTimestamp "2013-09-25T13:22:05.902+03:00"^^xsd:dateTime ;
  :dialogType pvn:message ;
  a :Form ;
  :dialogDataRoot [] ;
  :rootGroup _:BN00002e .
_:BN00001b :groupChildren [
      :parentControl _:BN00001b ;
      :theContent "Window is open"^^xsd:string ;
      a :SimpleOutput
    ] ,
    [
      :parentControl _:BN00001b ;
      :contentURL "bundle://97.0:1/images/opened_window.png"^^xsd:string ;
      a :MediaObject ;
      :contentType "image/png"^^xsd:string ;
      :controlLabel [
        a :Label ;
        rdfs:label "Window"^^xsd:string
      ]
    ] ;
  :parentControl _:BN00000c ;
  a :Group ;
  :controlLabel [
    a :Label ;
    rdfs:label "ioControlsGroup"^^xsd:string
  ] .
_:BN00001c :groupChildren [
      :parentControl _:BN00001c ;
      pvn:submissionID "deleteMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN00001a
    ] ,
    [
      :parentControl _:BN00001c ;
      pvn:submissionID "preserveMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN000043
    ] ;
  a :Group ;
  :parentControl _:BN00001f ;
  :controlLabel [
    a :Label ;
    rdfs:label "submitsGroup"^^xsd:string
  ] .
_:BN00001d a :Label ;
  rdfs:label "Preserve"^^xsd:string .
_:BN00001e :groupChildren [
      :parentControl _:BN00001e ;
      pvn:submissionID "deleteMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN00004f
    ] ,
    [
      :parentControl _:BN00001e ;
      pvn:submissionID "preserveMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN00004d
    ] ;
  a :Group ;
  :parentControl _:BN00003c ;
  :controlLabel [
    a :Label ;
    rdfs:label "submitsGroup"^^xsd:string
  ] .
ns6:off a ns6:Status .
_:BN00001f :groupChildren _:BN00001c ,
    _:BN00002a ;
  a :Group ;
  :parentControl <http://ontology.universAAL.org/Dialog.owl#_:a0283ced6e2d5d98:155b> ;
  :controlLabel [
    a :Label ;
    rdfs:label "New Window Alert Message"^^xsd:string
  ] .
_:BN000020 :groupChildren _:BN00003e ,
    _:BN00003d ;
  a :Group ;
  :parentControl <http://ontology.universAAL.org/Dialog.owl#_:a0283ced878a1a82:18ff> ;
  :controlLabel [
    a :Label ;
    rdfs:label "Visitor Alert Message"^^xsd:string
  ] .
ns7:saiedSubprofileUIPreferencesAlertPreferences ns6:alertOption ns6:visualAndAudio ;
  a ns6:AlertPreferences .
_:BN000021 :groupChildren [
      :parentControl _:BN000021 ;
      :theContent "Unknown Person is knocking on the door."^^xsd:string ;
      a :SimpleOutput
    ] ,
    [
      :parentControl _:BN000021 ;
      :contentURL "http://127.0.0.1:8080/resources/safety/images/Unknown_Person.png"^^xsd:string ;
      a :MediaObject ;
      :contentType "image/png"^^xsd:string ;
      :controlLabel [
        a :Label ;
        rdfs:label ""^^xsd:string
      ]
    ] ;
  a :Group ;
  :parentControl _:BN000012 ;
  :controlLabel [
    a :Label ;
    rdfs:label "ioControlsGroup"^^xsd:string
  ] .
<http://ontology.universAAL.org/Dialog.owl#_:a0283ced36028ef4:1a1f> :creationTimestamp "2013-09-25T11:35:18.160+03:00"^^xsd:dateTime ;
  :dialogType pvn:message ;
  a :Form ;
  :dialogDataRoot [] ;
  :rootGroup _:BN000045 .
pvn:message a pvn:DialogType .
_:BN000022 :groupChildren [
      :parentControl _:BN000022 ;
      :theContent "Lights are on"^^xsd:string ;
      a :SimpleOutput
    ] ,
    [
      :parentControl _:BN000022 ;
      :contentURL "http://127.0.0.1:8080/resources/safety/images/light_on.png"^^xsd:string ;
      a :MediaObject ;
      :contentType "image/png"^^xsd:string ;
      :controlLabel [
        a :Label ;
        rdfs:label ""^^xsd:string
      ]
    ] ;
  a :Group ;
  :parentControl _:BN000048 ;
  :controlLabel [
    a :Label ;
    rdfs:label "ioControlsGroup"^^xsd:string
  ] .
ns6:visualAndAudio a ns6:AlertType .
_:BN000023 a :Label ;
  rdfs:label "Preserve"^^xsd:string .
_:BN000024 :groupChildren [
      :parentControl _:BN000024 ;
      pvn:submissionID "deleteMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN00004b
    ] ,
    [
      :parentControl _:BN000024 ;
      pvn:submissionID "preserveMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN000023
    ] ;
  a :Group ;
  :parentControl _:BN000048 ;
  :controlLabel [
    a :Label ;
    rdfs:label "submitsGroup"^^xsd:string
  ] .
_:BN000025 :groupChildren [
      :parentControl _:BN000025 ;
      :theContent "Lights are on"^^xsd:string ;
      a :SimpleOutput
    ] ,
    [
      :parentControl _:BN000025 ;
      :contentURL "bundle://88.0:1/images/light_on.png"^^xsd:string ;
      a :MediaObject ;
      :contentType "image/png"^^xsd:string ;
      :controlLabel [
        a :Label ;
        rdfs:label ""^^xsd:string
      ]
    ] ;
  :parentControl _:BN00002c ;
  a :Group ;
  :controlLabel [
    a :Label ;
    rdfs:label "ioControlsGroup"^^xsd:string
  ] .
_:BN000026 :groupChildren _:BN000044 ,
    _:BN000036 ;
  a :Group ;
  :parentControl <http://ontology.universAAL.org/Dialog.owl#_:a0283ced53b25bb2:19bc> ;
  :controlLabel [
    a :Label ;
    rdfs:label "Door Alert Message"^^xsd:string
  ] .
_:BN000027 :groupChildren [
      :parentControl _:BN000027 ;
      :theContent "Lights are on"^^xsd:string ;
      a :SimpleOutput
    ] ,
    [
      :parentControl _:BN000027 ;
      :contentURL "http://127.0.0.1:8080/resources/safety/images/light_on.png"^^xsd:string ;
      a :MediaObject ;
      :contentType "image/png"^^xsd:string ;
      :controlLabel [
        a :Label ;
        rdfs:label ""^^xsd:string
      ]
    ] ;
  a :Group ;
  :parentControl _:BN000038 ;
  :controlLabel [
    a :Label ;
    rdfs:label "ioControlsGroup"^^xsd:string
  ] .
<http://ontology.universAAL.org/Dialog.owl#_:a0283cedac41bf30:18bf> :creationTimestamp "2013-09-05T14:21:54.330+03:00"^^xsd:dateTime ;
  :dialogType pvn:message ;
  a :Form ;
  :dialogDataRoot [] ;
  :rootGroup _:BN000032 .
ns6:detailed a ns6:ContentDensityType .
<http://ontology.universAAL.org/Dialog.owl#_:a0283ced64a4159b:1632> :creationTimestamp "2013-09-05T11:08:56.973+03:00"^^xsd:dateTime ;
  :dialogType pvn:message ;
  a :Form ;
  :dialogDataRoot [] ;
  :rootGroup _:BN000049 .
_:BN000028 :groupChildren _:BN000017 ,
    _:BN00002f ;
  :parentControl <http://ontology.universAAL.org/Dialog.owl#_:a0283ced878a1a82:18e1> ;
  a :Group ;
  :controlLabel [
    a :Label ;
    rdfs:label "Visitor Alert Message"^^xsd:string
  ] .
_:BN000029 a :Label ;
  rdfs:label "Delete"^^xsd:string .
<http://ontology.universAAL.org/Dialog.owl#_:a0283ced878a1a82:18e1> :creationTimestamp "2013-09-25T13:22:05.751+03:00"^^xsd:dateTime ;
  :dialogType pvn:message ;
  a :Form ;
  :dialogDataRoot [] ;
  :rootGroup _:BN000028 .
_:BN00002a :groupChildren [
      :parentControl _:BN00002a ;
      :theContent "Window is oopen"^^xsd:string ;
      a :SimpleOutput
    ] ,
    [
      :parentControl _:BN00002a ;
      :contentURL "http://127.0.0.1:8080/resources/safety/images/opened_window_s.png"^^xsd:string ;
      a :MediaObject ;
      :contentType "image/png"^^xsd:string ;
      :controlLabel [
        a :Label ;
        rdfs:label "Window"^^xsd:string
      ]
    ] ;
  :parentControl _:BN00001f ;
  a :Group ;
  :controlLabel [
    a :Label ;
    rdfs:label "ioControlsGroup"^^xsd:string
  ] .
_:BN00002b a :Label ;
  rdfs:label "Delete"^^xsd:string .
_:BN00002c :groupChildren _:BN000035 ,
    _:BN000025 ;
  a :Group ;
  :parentControl <http://ontology.universAAL.org/Dialog.owl#_:a0283cedf5b165c5:1488> ;
  :controlLabel [
    a :Label ;
    rdfs:label "Lights Alert Message"^^xsd:string
  ] .
_:BN00002d :groupChildren [
      :parentControl _:BN00002d ;
      :theContent "Unknown Person is knocking on the door."^^xsd:string ;
      a :SimpleOutput
    ] ,
    [
      :parentControl _:BN00002d ;
      :contentURL "http://127.0.0.1:8080/resources/safety/images/Unknown_Person.png"^^xsd:string ;
      a :MediaObject ;
      :contentType "image/png"^^xsd:string ;
      :controlLabel [
        a :Label ;
        rdfs:label ""^^xsd:string
      ]
    ] ;
  a :Group ;
  :parentControl _:BN00002e ;
  :controlLabel [
    a :Label ;
    rdfs:label "ioControlsGroup"^^xsd:string
  ] .
_:BN00002e :groupChildren _:BN00002d ,
    _:BN000013 ;
  :parentControl <http://ontology.universAAL.org/Dialog.owl#_:a0283ced878a1a82:18f0> ;
  a :Group ;
  :controlLabel [
    a :Label ;
    rdfs:label "Visitor Alert Message"^^xsd:string
  ] .
_:BN00002f :groupChildren [
      :parentControl _:BN00002f ;
      pvn:submissionID "deleteMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN000014
    ] ,
    [
      :parentControl _:BN00002f ;
      pvn:submissionID "preserveMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN000019
    ] ;
  :parentControl _:BN000028 ;
  a :Group ;
  :controlLabel [
    a :Label ;
    rdfs:label "submitsGroup"^^xsd:string
  ] .
_:BN000030 :groupChildren [
      :parentControl _:BN000030 ;
      pvn:submissionID "deleteMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel [
        a :Label ;
        rdfs:label "Delete"^^xsd:string
      ]
    ] ,
    [
      :parentControl _:BN000030 ;
      pvn:submissionID "preserveMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel [
        a :Label ;
        rdfs:label "Preserve"^^xsd:string
      ]
    ] ;
  a :Group ;
  :parentControl _:BN000047 ;
  :controlLabel [
    a :Label ;
    rdfs:label "submitsGroup"^^xsd:string
  ] .
_:BN000031 :groupChildren [
      :parentControl _:BN000031 ;
      :theContent "Window is open"^^xsd:string ;
      a :SimpleOutput
    ] ,
    [
      :parentControl _:BN000031 ;
      :contentURL "bundle://88.0:1/images/opened_window.png"^^xsd:string ;
      a :MediaObject ;
      :contentType "image/png"^^xsd:string ;
      :controlLabel [
        a :Label ;
        rdfs:label "Window"^^xsd:string
      ]
    ] ;
  :parentControl _:BN00000d ;
  a :Group ;
  :controlLabel [
    a :Label ;
    rdfs:label "ioControlsGroup"^^xsd:string
  ] .
pvn:voice a pvn:Modality .
<http://ontology.universAAL.org/Dialog.owl#_:a0283ced36028ef4:1a0f> :creationTimestamp "2013-09-25T11:35:13.161+03:00"^^xsd:dateTime ;
  :dialogType pvn:message ;
  a :Form ;
  :dialogDataRoot [] ;
  :rootGroup _:BN000003 .
_:BN000032 :groupChildren _:BN000005 ,
    _:BN000034 ;
  a :Group ;
  :parentControl <http://ontology.universAAL.org/Dialog.owl#_:a0283cedac41bf30:18bf> ;
  :controlLabel [
    a :Label ;
    rdfs:label "Window Alert Message"^^xsd:string
  ] .
_:BN000033 :groupChildren _:BN00004e ,
    _:BN000051 ;
  a :Group ;
  :parentControl <http://ontology.universAAL.org/Dialog.owl#_:a0283ced344fcf99:1664> ;
  :controlLabel [
    a :Label ;
    rdfs:label "New Lights Alert Message"^^xsd:string
  ] .
_:BN000034 :groupChildren [
      :parentControl _:BN000034 ;
      :theContent "Window is open"^^xsd:string ;
      a :SimpleOutput
    ] ,
    [
      :parentControl _:BN000034 ;
      :contentURL "http://127.0.0.1:8080/resources/safety/images/opened_window.png"^^xsd:string ;
      a :MediaObject ;
      :contentType "image/png"^^xsd:string ;
      :controlLabel [
        a :Label ;
        rdfs:label "Window"^^xsd:string
      ]
    ] ;
  :parentControl _:BN000032 ;
  a :Group ;
  :controlLabel [
    a :Label ;
    rdfs:label "ioControlsGroup"^^xsd:string
  ] .
_:BN000035 :groupChildren [
      :parentControl _:BN000035 ;
      pvn:submissionID "deleteMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN000029
    ] ,
    [
      :parentControl _:BN000035 ;
      pvn:submissionID "preserveMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN000055
    ] ;
  :parentControl _:BN00002c ;
  a :Group ;
  :controlLabel [
    a :Label ;
    rdfs:label "submitsGroup"^^xsd:string
  ] .
_:BN000036 :groupChildren [
      :parentControl _:BN000036 ;
      pvn:submissionID "deleteMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN00002b
    ] ,
    [
      :parentControl _:BN000036 ;
      pvn:submissionID "preserveMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN000018
    ] ;
  :parentControl _:BN000026 ;
  a :Group ;
  :controlLabel [
    a :Label ;
    rdfs:label "submitsGroup"^^xsd:string
  ] .
_:BN000037 :groupChildren _:BN000039 ,
    _:BN000053 ;
  :parentControl <http://ontology.universAAL.org/Dialog.owl#_:a0283cedf5b165c5:1793> ;
  a :Group ;
  :controlLabel [
    a :Label ;
    rdfs:label "Lights Alert Message"^^xsd:string
  ] .
ns6:black a ns6:ColorType .
<http://ontology.universAAL.org/Dialog.owl#_:a0283cedac41bf30:22f2> :creationTimestamp "2013-09-05T14:28:31.648+03:00"^^xsd:dateTime ;
  :dialogType pvn:message ;
  a :Form ;
  :dialogDataRoot [] ;
  :rootGroup _:BN000048 .
<http://ontology.universAAL.org/Dialog.owl#_:a0283ced64a4159b:1623> :creationTimestamp "2013-09-05T11:08:56.558+03:00"^^xsd:dateTime ;
  :dialogType pvn:message ;
  a :Form ;
  :dialogDataRoot [] ;
  :rootGroup _:BN00000c .
_:BN000038 :groupChildren _:BN000027 ,
    _:BN00004c ;
  a :Group ;
  :parentControl <http://ontology.universAAL.org/Dialog.owl#_:a0283cedac41bf30:1923> ;
  :controlLabel [
    a :Label ;
    rdfs:label "Lights Alert Message 0"^^xsd:string
  ] .
_:BN000039 :groupChildren [
      :parentControl _:BN000039 ;
      pvn:submissionID "deleteMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN000029
    ] ,
    [
      :parentControl _:BN000039 ;
      pvn:submissionID "preserveMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN000055
    ] ;
  a :Group ;
  :parentControl _:BN000037 ;
  :controlLabel [
    a :Label ;
    rdfs:label "submitsGroup"^^xsd:string
  ] .
_:BN00003a :groupChildren _:BN00004a ,
    _:BN000040 ;
  a :Group ;
  :parentControl <http://ontology.universAAL.org/Dialog.owl#_:a0283ced53b25bb2:196a> ;
  :controlLabel [
    a :Label ;
    rdfs:label "Door Alert Message"^^xsd:string
  ] .
_:BN00003b :groupChildren [
      :parentControl _:BN00003b ;
      :theContent "Door is open"^^xsd:string ;
      a :SimpleOutput
    ] ,
    [
      :parentControl _:BN00003b ;
      :contentURL "http://127.0.0.1:8080/resources/safety/images/door_open.png"^^xsd:string ;
      a :MediaObject ;
      :contentType "image/png"^^xsd:string ;
      :controlLabel [
        a :Label ;
        rdfs:label "Door"^^xsd:string
      ]
    ] ;
  a :Group ;
  :parentControl _:BN00003c ;
  :controlLabel [
    a :Label ;
    rdfs:label "ioControlsGroup"^^xsd:string
  ] .
_:BN00003c :groupChildren _:BN00001e ,
    _:BN00003b ;
  a :Group ;
  :parentControl <http://ontology.universAAL.org/Dialog.owl#_:a0283ced36028ef4:1a00> ;
  :controlLabel [
    a :Label ;
    rdfs:label "Door Alert Message"^^xsd:string
  ] .
_:BN00003d :groupChildren [
      :parentControl _:BN00003d ;
      pvn:submissionID "deleteMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN000014
    ] ,
    [
      :parentControl _:BN00003d ;
      pvn:submissionID "preserveMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN000019
    ] ;
  :parentControl _:BN000020 ;
  a :Group ;
  :controlLabel [
    a :Label ;
    rdfs:label "submitsGroup"^^xsd:string
  ] .
_:BN00003e :groupChildren [
      :parentControl _:BN00003e ;
      :theContent "Unknown Person is knocking on the door."^^xsd:string ;
      a :SimpleOutput
    ] ,
    [
      :parentControl _:BN00003e ;
      :contentURL "http://127.0.0.1:8080/resources/safety/images/Unknown_Person.png"^^xsd:string ;
      a :MediaObject ;
      :contentType "image/png"^^xsd:string ;
      :controlLabel [
        a :Label ;
        rdfs:label ""^^xsd:string
      ]
    ] ;
  :parentControl _:BN000020 ;
  a :Group ;
  :controlLabel [
    a :Label ;
    rdfs:label "ioControlsGroup"^^xsd:string
  ] .
_:BN00003f a :Label ;
  rdfs:label "Delete"^^xsd:string .
_:BN000040 :groupChildren [
      :parentControl _:BN000040 ;
      :theContent "Door is open"^^xsd:string ;
      a :SimpleOutput
    ] ,
    [
      :parentControl _:BN000040 ;
      :contentURL "http://127.0.0.1:8080/resources/safety/images/door_open.png"^^xsd:string ;
      a :MediaObject ;
      :contentType "image/png"^^xsd:string ;
      :controlLabel [
        a :Label ;
        rdfs:label "Door"^^xsd:string
      ]
    ] ;
  :parentControl _:BN00003a ;
  a :Group ;
  :controlLabel [
    a :Label ;
    rdfs:label "ioControlsGroup"^^xsd:string
  ] .
_:BN000041 :groupChildren [
      :parentControl _:BN000041 ;
      pvn:submissionID "deleteMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN00003f
    ] ,
    [
      :parentControl _:BN000041 ;
      pvn:submissionID "preserveMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN00001d
    ] ;
  a :Group ;
  :parentControl _:BN000049 ;
  :controlLabel [
    a :Label ;
    rdfs:label "submitsGroup"^^xsd:string
  ] .
ns1:saiedSubprofileUIPreferencesAlertPreferences ns6:alertOption ns6:visualAndAudio ;
  a ns6:AlertPreferences .
ns6:high a ns6:Intensity .
_:BN000042 a :Label ;
  rdfs:label "Preserve"^^xsd:string .
_:BN000043 a :Label ;
  rdfs:label "Preserve"^^xsd:string .
_:BN000044 :groupChildren [
      :parentControl _:BN000044 ;
      :theContent "Door is open"^^xsd:string ;
      a :SimpleOutput
    ] ,
    [
      :parentControl _:BN000044 ;
      :contentURL "http://127.0.0.1:8080/resources/safety/images/door_open.png"^^xsd:string ;
      a :MediaObject ;
      :contentType "image/png"^^xsd:string ;
      :controlLabel [
        a :Label ;
        rdfs:label "Door"^^xsd:string
      ]
    ] ;
  :parentControl _:BN000026 ;
  a :Group ;
  :controlLabel [
    a :Label ;
    rdfs:label "ioControlsGroup"^^xsd:string
  ] .
_:BN000045 :groupChildren _:BN00000f ,
    _:BN00000e ;
  a :Group ;
  :parentControl <http://ontology.universAAL.org/Dialog.owl#_:a0283ced36028ef4:1a1f> ;
  :controlLabel [
    a :Label ;
    rdfs:label "Door Alert Message"^^xsd:string
  ] .
_:BN000046 :groupChildren [
      :parentControl _:BN000046 ;
      :theContent "Window is open"^^xsd:string ;
      a :SimpleOutput
    ] ,
    [
      :parentControl _:BN000046 ;
      :contentURL "bundle://88.0:1/images/opened_window.png"^^xsd:string ;
      a :MediaObject ;
      :contentType "image/png"^^xsd:string ;
      :controlLabel [
        a :Label ;
        rdfs:label "Window"^^xsd:string
      ]
    ] ;
  a :Group ;
  :parentControl _:BN000047 ;
  :controlLabel [
    a :Label ;
    rdfs:label "ioControlsGroup"^^xsd:string
  ] .
_:BN000047 :groupChildren _:BN000030 ,
    _:BN000046 ;
  :parentControl <http://ontology.universAAL.org/Dialog.owl#_:a0283cedac8934a:13e5> ;
  a :Group ;
  :controlLabel [
    a :Label ;
    rdfs:label "Window Alert Message"^^xsd:string
  ] .
pvn:insensible a pvn:PrivacyLevel .
ns7:saiedSubprofileUIPreferencesGeneralInteractionPreferences ns6:secondaryLanguage ns8:greek ;
  ns6:secondaryModality pvn:voice ;
  a ns6:GeneralInteractionPreferences ;
  ns6:contentDensity ns6:detailed ;
  ns6:preferredLanguage ns8:greek ;
  ns6:preferredModality pvn:gui .
_:BN000048 :groupChildren _:BN000022 ,
    _:BN000024 ;
  a :Group ;
  :parentControl <http://ontology.universAAL.org/Dialog.owl#_:a0283cedac41bf30:22f2> ;
  :controlLabel [
    a :Label ;
    rdfs:label "Lights Alert Message 1"^^xsd:string
  ] .
_:BN000049 :groupChildren _:BN000052 ,
    _:BN000041 ;
  a :Group ;
  :parentControl <http://ontology.universAAL.org/Dialog.owl#_:a0283ced64a4159b:1632> ;
  :controlLabel [
    a :Label ;
    rdfs:label "Lights Alert Message"^^xsd:string
  ] .
_:BN00004a :groupChildren [
      :parentControl _:BN00004a ;
      pvn:submissionID "deleteMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN00002b
    ] ,
    [
      :parentControl _:BN00004a ;
      pvn:submissionID "preserveMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN000018
    ] ;
  :parentControl _:BN00003a ;
  a :Group ;
  :controlLabel [
    a :Label ;
    rdfs:label "submitsGroup"^^xsd:string
  ] .
_:BN00004b a :Label ;
  rdfs:label "Delete"^^xsd:string .
_:BN00004c :groupChildren [
      :parentControl _:BN00004c ;
      pvn:submissionID "deleteMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN00004b
    ] ,
    [
      :parentControl _:BN00004c ;
      pvn:submissionID "preserveMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN000023
    ] ;
  :parentControl _:BN000038 ;
  a :Group ;
  :controlLabel [
    a :Label ;
    rdfs:label "submitsGroup"^^xsd:string
  ] .
_:BN00004d a :Label ;
  rdfs:label "Preserve"^^xsd:string .
_:BN00004e :groupChildren [
      :parentControl _:BN00004e ;
      :theContent "Lights are oon"^^xsd:string ;
      a :SimpleOutput
    ] ,
    [
      :parentControl _:BN00004e ;
      :contentURL "http://127.0.0.1:8080/resources/safety/images/light_on_s.png"^^xsd:string ;
      a :MediaObject ;
      :contentType "image/png"^^xsd:string ;
      :controlLabel [
        a :Label ;
        rdfs:label "Lights"^^xsd:string
      ]
    ] ;
  :parentControl _:BN000033 ;
  a :Group ;
  :controlLabel [
    a :Label ;
    rdfs:label "ioControlsGroup"^^xsd:string
  ] .
_:BN00004f a :Label ;
  rdfs:label "Delete"^^xsd:string .
<http://ontology.universAAL.org/Dialog.owl#_:a0283ced36028ef4:1a00> :creationTimestamp "2013-09-25T11:35:08.159+03:00"^^xsd:dateTime ;
  :dialogType pvn:message ;
  a :Form ;
  :dialogDataRoot [] ;
  :rootGroup _:BN00003c .
_:BN000050 :groupChildren _:BN000056 ,
    _:BN000007 ;
  a :Group ;
  :parentControl <http://ontology.universAAL.org/Dialog.owl#_:a0283ced6e2d5d98:15d4> ;
  :controlLabel [
    a :Label ;
    rdfs:label "New Lights Alert Message"^^xsd:string
  ] .
_:BN000051 :groupChildren [
      :parentControl _:BN000051 ;
      pvn:submissionID "deleteMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN000054
    ] ,
    [
      :parentControl _:BN000051 ;
      pvn:submissionID "preserveMessage"^^xsd:string ;
      a :Submit ;
      :controlLabel _:BN000042
    ] ;
  :parentControl _:BN000033 ;
  a :Group ;
  :controlLabel [
    a :Label ;
    rdfs:label "submitsGroup"^^xsd:string
  ] .
