/*
   ENUMS:

   PERSON.ROLE (PATIENT, CAREGIVER, PHYSICIAN)
*/

CREATE TABLE CONTACT_MANAGER.PERSON (
  ID         INT NOT NULL,
  NAME            VARCHAR(77) NOT NULL,
  PERSON_URI     VARCHAR(144) NOT NULL,
  ROLE            VARCHAR(18) NOT NULL,
  CONSTRAINT PERSON_PK PRIMARY KEY (ID)
);



  
