CREATE TABLE CONTACT_MANAGER.VCARD (
  USER_URI                VARCHAR(144) NOT NULL,
  VCARD_VERSION           VARCHAR(40),
  LAST_REVISION           TIMESTAMP,
  NICKNAME                VARCHAR(50),
  DISPLAY_NAME            VARCHAR(100),
  UCI_LABEL               CLOB,
  UCI_ADDITIONAL_DATA     CLOB,
  ABOUT_ME                CLOB,
  BDAY                    TIMESTAMP,
  FN                      VARCHAR(144),
  CONSTRAINT VCARD_PK PRIMARY KEY (USER_URI)
);

CREATE TABLE CONTACT_MANAGER.TYPES (
  ID              INT NOT NULL,
  NAME            VARCHAR(20) NOT NULL,
  TYPE            VARCHAR(50) NOT NULL,
  VALUE           VARCHAR(80) NOT NULL,
  VCARD_FK        VARCHAR(144) NOT NULL,
  CONSTRAINT TYPES_PK PRIMARY KEY (ID),
  CONSTRAINT TYPES_VCARD_FK FOREIGN KEY (VCARD_FK)
    REFERENCES CONTACT_MANAGER.VCARD (USER_URI)
);


