// PERSON TABLE

INSERT INTO MEDICATION_MANAGER.PERSON (PERSON_ID, NAME, PERSON_URI, ROLE)
VALUES (3, 'Pijo', 'urn:org.universAAL.aal_space:test_env#pijo', 'patient');

INSERT INTO MEDICATION_MANAGER.PERSON (PERSON_ID, NAME, PERSON_URI, ROLE)
VALUES (4, 'd-r Penda Pendev', 'urn:org.universAAL.aal_space:test_env#penda', 'physician');

// MEDICINE TABLE

INSERT INTO MEDICATION_MANAGER.MEDICINE (MEDICINE_ID, MEDICINE_NAME, MEDICINE_INFO, SIDE_EFFECTS, INCOMPLIANCES, MEAL_RELATION)
VALUES (4, 'Centrum', 'Centrum description', 'Centrum side_effects', 'Centrum incompliances', 'after');



// MEDICINE_INVENTORY TABLE

INSERT INTO MEDICATION_MANAGER.MEDICINE_INVENTORY (ID, PATIENT_FK_ID, MEDICINE_FK_ID, UNIT_CLASS, QUANTITY, WARNING_THRESHOLD)
VALUES (4, 3, 4, 'pill', 200, 20);



// PRESCRIPTION TABLE

INSERT INTO MEDICATION_MANAGER.PRESCRIPTION (PRESCRIPTION_ID, TIME_OF_CREATION, PATIENT_FK_ID, PHYSICIAN_FK_ID, STATUS)
VALUES (2, '2013-01-17 17:07:36', 3, 4, 'y');





