#created on: 21-mar-2012
package contemplation

#list any import classes here.

#declare any global variables here

rule "Reinforce the decission"
	when
		// El usuario haya pasado a contemplation
	then 
		// Enviamos un mensaje al usuario para felicitarle por su decisión y 
		// le comentamos los beneficios que obtendrá por seguir el tratamiento.
end

rule "Schedule first session for flexible treatments"
	when
		// el tratamiento sea flexible y las reglas de schedule hayan 
		// acordado la fecha de la primera realización
	then 
		// enviar un mensaje al usuario con una propuesta sobre
		// la realización de la primera sesión 
		// mensaje con preguntas condicionales, así que si no le viene
		// bien, debe introducir la fecha que más le convenga, pero pidiéndole
		// que por favor no se demore mucho más de lo que indicaba la fecha propuesta
end


rule "Re-schedule fixed treatment planning"
	when
	//Cuando el tratamiento tenga sesiones planificadas y haya sesiones que no hayan sido realizadas 
	then 
	//Establecer la próxima sesión como la primera y alargar la fecha de fin añadiendo el número de sesiones no realizadas al calendario. Notificar al usuario de cuándo tendrá lugar la primera sesión. 
	//Avisar al caregiver para que indique o no si vale la reestructuración
end

rule "First session explanation"
	when
		// hoy tengo que enviar mensaje de explicación
	then 
		//Mesaje al usuario explicando la primera sesión, cómo tiene que hacer las cosas, dónde, qué necesita
		//preguntar si le quedan dudas -- conditional questions  
end

rule "Contact caregiver because of doubts"
	when
	// no se hayan podido responder las dudas al usuario
	then
	// contactar al caregiver para que las resuelva
end

rule "Advice for first-session's performance" 
	when
		// toque mandar un mensaje de consejo
	then 
	// mandar un mensaje al usuario sobre consejos para su sesión
end

rule "Remider of first session"
	
	when
		// sea un día antes de comenzar el tratamiento 
	then 
		//avisar al usuario para tenerlo todo preparado y decirle a qué hora tiene que hacerlo
end

rule "Reminder of first session hour"
	when
		//quede una hora para empezar la sesión
	then 
		//se le manda un mensaje al usuario recordándoselo y dándole ánimos
		
end

rule "First Session performed"  no-loop
	
	when
	// se detecte la primera sesión haya sido realizada 
	then
	//se almacena en un array de sesiones completadas (add Performed Session a treatment también).
	//aumenta una unidad la completitud del tratamiento
end

rule "Non-fullfilment of first session (first time)"  no-loop
	
	when
	// se detecte que la primera sesión no haya sido realizada 
	then
	// Enviar al usuario un cuestionario condicional para averiguar causa si la causa fue la destreza.
	//Se introduce la sesión en array de sesiones no realizadas

end

rule "The cause was an oversight"  no-loop
	
	when
	// las respuestas al mensaje anterior indiquen que la causa no fue la destreza
	then
	//Causa fue el olvido 
	//Enviar al usuario un mensaje para reforzar la memoria (trigger visual o asociación).
	//Planificación de la siguiente sesión (día siguiente si el tratamiento es flexible) 

end

rule "The cause was the lack of (destreza) "  no-loop
	
	when
	// las respuestas al mensaje anterior indiquen que la causa fue la destreza
	then
	//Enviar al usuario un mensaje para solventar la destreza.
	//Planificación de la siguiente sesión (día siguiente si el tratamiento es flexible) 

end

rule "Non-fullfilment of first session (second time)"  no-loop
	
	when
	// se detecte que la primera sesión no haya sido realizada por segunda vez
	then
	// Enviar al usuario un cuestionario condicional para averiguar causa si la causa fue el sentimiento.
	//Se introduce la sesión en array de sesiones no realizadas

end

rule "The cause was a feeling"  no-loop
	when
	// las respuestas al mensaje anterior indiquen que la causa fue un temor, un sentimiento
	then
	//Enviar al usuario un mensaje para solventar el problema.
	//Planificación de la siguiente sesión (día siguiente si el tratamiento es flexible) 
end

rule "Non-fullfilment of first session (third time)"  no-loop
	
	when
	// se detecte que la primera sesión no haya sido realizada por tercera vez
	then
	// Cambio de estado.
	// Notificar al caregiver
end

rule "Confirmation of first session performance"
	when
	// Hoy tocase hacer la sesión y el tratamiento no lleva asociado medida
	then
	// preguntar al usuario si hizo la sesión
end