#created on: 11-nov-2011
package org.universAAL.AALApplication.health.motivation.feedback

#list any import classes here.
import org.universAAL.AALapplication.health.ont.healthMeasurement.*;
import org.universAAL.AALapplication.health.ont.treatment.*;
import org.universAAL.AALapplication.health.ont.schedule.*; 
import org.universAAL.AALApplication.health.motivation.treatment.HealthService;


#declare any global variables here

/**
* This rule checks if the detected measurement is between the safety range. If not, the rule
* fires and send a message to the user, to warn him/her
*/

rule "Check detected health measurements" no-loop
	when
		
		HealthMeasurement($maxm:associatedTreatment.maxMeasurementAllowed, $minm:associatedTreatment.minMeasurementAllowed)
		hm: HealthMeasurement( detectedMeasurement > $maxm || detectedMeasurement < $minm)
		
	then
		HealthService.sendMessage(30, "Measurement out of safety range"); //preguntar al usuario el por qué y/o avisar al caregiver
		System.out.println("Measurement out of safety range");
		//MeasurementDetectionTest.insertHTreatment(hm);
		MeasurementDetectionTest.hmOutOfRange.add(hm); //sólo válido para el JUnit
	
end


rule "Associate health measurement to treatment"
	when
		measurement: HealthMeasurement()
	then 
		#actions
		
end
