#created on: 21-mar-2012
package precontemplation

#list any import classes here.
#declare any global variables here

//variable: ciclo de indagación, ciclo de motivación básico/avanzado, ciclo de educación básico/avanzado
//variable (integer): feeling_threshold, ignorance_threshold, conviction. 
//variable: cause_determinated = false;

rule "Similar treatment already done"
when
	//el paciente realizó ya un tratamiento de este tipo y lo terminó
then
	// aumentar en una unidad el umbral de convicción
end 


rule "Similar treatment already started before"
when
	//el paciente realizó ya un tratamiento de este tipo pero NO lo terminó
then
	// aumentar en una unidad el umbral de sentimiento
end 

# CICLO DE INVESTIGACIÓN

rule "Beginning of cicle of investigation (initial)" ruleflow-group "Investigation cycle" 
	
	when
		//el paciente esté en estado precontemplation y NO llegue de una etapa más anterior
		
	then 
		//poner ciclo de indagación a true
end

rule "Send inquiry messages for investigation cycle"
	
	when
		// ciclo de investigación esté a true y 
		// hoy toque mandar un mensaje de inquiry
	then 
		// mandar mensaje de investigación (preguntas relacionadas con los sentimientos)
		
end

rule "Check inquiry results"
	when
		// cada vez que se reciba una respuesta a un mensaje inquiry
		// y el 60% de las respuestas es correcto (establecemos como correct answer aquella que 
		// asociamos a un comportamiento de sentimiento
	then 
		//aumentar el umbral de feeling en una unidad
end

rule "Send tests messages"

	when
		// ciclo de investigación esté a true y 
		// hoy toque mandar un mensaje de test
	then 
		// mandar un test de conocimientos, en base a la enfermedad del paciente.
end

rule "Check test results"
	when
		// cada vez que se reciba una respuesta a un mensaje inquiry
		// y el 60% de las respuestas es correcto (establecemos como correct answer aquella que 
		// asociamos a un comportamiento de sentimiento
	then 
		//aumentar el umbral de ignorance en una unidad
end

rule "Message pending reminder"
	when
	//Se haya mandado un mensaje al usuario ese día
	// y no se haya recibido la respuesta del usuario una hora antes de que se acueste el usuario
	
	then 
	//Enviar un mensaje al usuario con todos los mensajes que tiene pendientes de respuesta y pedirle que los rellene.
end


rule "Cicle of investigation done"
	when
		// cuando haya acabado la duración del ciclo de investigación
		
	then 
	// poner ciclo de investigación a false
		// si se han respondido al menos 3 mensajes y el umbral de ignorance es 3 o + --> causa=ignorancia (activar ciclo de educación)
		// si se han respondido al menos 3 mensajes y el umbral de feeling es 3 o + --> causa=sentimiento (activar ciclo de motivación)
		// si se han respondido los 10 mensajes y el umbral de ignorance y de feeling es 0 --> causa=convicción
		// si no hay ningún mensaje respondido --> causa=convicción
		// si se han respondido 2 o menos mensajes y el umbral feeling es 2 o 1 --> causa=sentimiento (activar ciclo de motivación)
		// si se han respondido 2 o menos mensajes y el umbral ignorance es 2 o 1 --> causa=ignorancia (activar ciclo de educación)
		// para el resto de casos--> causa=convicción
		
end

rule "Set the cause as ignorance"
	when
	//El ciclo de investigación haya terminado
	// y se han respondido al menos 3 mensajes y el umbral de ignorance es 3 o +) o 
	// (si se han respondido 2 o menos mensajes y el umbral ignorance es 2 o 1 		
	then 
	// establecer como causa=ignorancia 
	// (activar ciclo de educación)
						
end

rule "Set the cause as feeling"
	when
	//El ciclo de investigación haya terminado
	//Y si se han respondido al menos 3 mensajes y el umbral de feeling es 3 o +) o 
	//(si se han respondido 2 o menos mensajes y el umbral feeling es 2 o 1)

then	
	//establecer como causa=sentimiento 
	//(activar ciclo de motivación)
end

rule "Set the cause as conviction"
	when
	//El ciclo de investigación haya terminado
	//Y no se hayan respondido los mensajes o 
	//umbrales de ignorancia y sentimiento son cero 		
	then 
	//establecer causa=convicción
	//Notificar al caregiver que el usuario no está por la labor de realizar el tratamiento, 
	//para que éste actúe en consecuencia (por ejemplo, cancelando el tratamiento o proponiendo otro distinto). 
end

#CICLO DE EDUCACIÓN

rule "Basic educational cycle active"
	when
	// educationalCycle = true
	// y hoy toque mandar un mensaje educativo
	then 
	//mandar mensajes educativos al usuario sobre su enfermedad
end

rule "Advanced educational cycle activation"
	
	when
		//el paciente esté en estado precontemplation y llegue de una etapa más anterior
		// y sea ignorante
		
	then 
		//poner ciclo de educación avanzada a true
end

rule "Advanced educational cycle active"
	when
	// advancedEducationalCycle = true
	// y hoy toque mandar un mensaje educativo
	then 
	//mandar mensajes educativos al usuario sobre su enfermedad
end

rule "Educational cycle termination"
	when
	// Hoy acabe el ciclo de educación
	then 
	// educationalCycle = false;
end

#CICLO DE MOTIVACIÓN

rule "Motivational cycle active"
	when
	// motivationalCycle = true
	// y hoy toque mandar un mensaje motivador
	then 
	//Enviar mensajes motivadores al usuario para reforzar la esperanza y reforzar el positivismo.
end

rule "Motivational cycle termination"
	when
	// Hoy acabe el ciclo de motivación
	then 
	// motivationalCycle = false;
end
rule "Advanced motivational cycle activation"
	
	when
		//el paciente esté en estado precontemplation y llegue de una etapa más anterior
		// y sea miedoso
		
	then 
		//poner ciclo de motivación avanzada a true
end

rule "Advanced motivational cycle active"
	when
	// advancedMotivationalCycle = true
	// y hoy toque mandar un mensaje motivacional
	then 
	//mandar mensajes motivacionales al usuario
end


# POSIBLE CAMBIO DE FASE
rule "Predisposition to contemplation"
	when
	//Hayan acabado los ciclos de educación y motivación
	then 
	// Preguntar al usuario si pretende realizar el tratamiento
end

rule "Precontemplation phase finished succesfully"
	when
	//La respuesta a alguno de los mensajes anteriores es afirmativa 
	then 
	//Cambiar el estado motivacional del paciente a contemplation.
	//Notificar al caregiver de que la estrategia motivadora ha sido un éxito y el usuario ha decidido realizar el tratamiento.
	//Enviar mensaje al usuario para reforzar su decisión.
	//Se cancela el ciclo de reglas de precontemplation para que el estado del tratamiento pueda cambiar a active (deja de ser posposed).
end

rule "Precontemplation phase finished unsuccesfully"
	when
	//La respuesta a TODOS los mensajes anteriores es negativa
	then 
	//Notificar al caregiver de que el usuario no quiere realizar el tratamiento por la causa que sea (ignorancia o sentimiento),
	//para que éste actúe en consecuencia (por ejemplo, cancelando el tratamiento o proponiendo otro distinto). 
end









