/*

ENUMS:

ROLE (PATIENT, CAREGIVER, PHYSICIAN)


UNIT_CLASS (PILLS, DROPS)


REFERENCE (INTAKE, REFILL)

STATUS (ACTIVE, INACTIVE)

MEAL_RELATION (BEFORE, WITH_MEAL, AFTER, ANY)

STATUS ("planned","actived","finished","cancelled", "prolonged")

*/

CREATE TABLE MEDICATION_MANAGER.PERSON (
  PERSON_ID         INT NOT NULL,
  NAME            VARCHAR(77) NOT NULL,
  PERSON_URI     VARCHAR(144) NOT NULL,
  ROLE            VARCHAR(18) NOT NULL,
  CONSTRAINT PERSON_PK PRIMARY KEY (PERSON_ID)
);

CREATE TABLE MEDICATION_MANAGER.MEDICINE (
  MEDICINE_ID     INT NOT NULL,
  MEDICINE_NAME   VARCHAR(77) NOT NULL,
  MEDICINE_INFO LONG VARCHAR,
  SIDE_EFFECTS LONG VARCHAR,
  INCOMPLIANCES LONG VARCHAR,
  MEAL_RELATION   VARCHAR(36) NOT NULL,
  CONSTRAINT MEDICINE_PK PRIMARY KEY (MEDICINE_ID)
);

CREATE TABLE MEDICATION_MANAGER.DISPENSER (
  DISPENESER_ID  INT NOT NULL,
  PATIENT_FK_ID  INT NOT NULL,
  DISPENSER_URI  VARCHAR(144) NOT NULL,

  CONSTRAINT DISPENSER_PK PRIMARY KEY (DISPENESER_ID),
  CONSTRAINT DISPENSER_PATIENT_FK FOREIGN KEY (PATIENT_FK_ID)
    REFERENCES MEDICATION_MANAGER.PERSON (PERSON_ID)
);

CREATE TABLE MEDICATION_MANAGER.MEDICINE_INVENTORY
(
    ID INT NOT NULL,
    PATIENT_FK_ID INT NOT NULL,
    MEDICINE_FK_ID INT NOT NULL,
    UNIT_CLASS VARCHAR(666) NOT NULL,
    QUANTITY INT NOT NULL,
    WARNING_THRESHOLD INT NOT NULL,

  CONSTRAINT MEDICINE_INVENTORY_PK PRIMARY KEY (ID),
  CONSTRAINT MEDICINE_INVENTORY_PATIENT_FK FOREIGN KEY (PATIENT_FK_ID)
       REFERENCES MEDICATION_MANAGER.PERSON (PERSON_ID),
  CONSTRAINT MEDICINE_INVENTORY_MEDICINE_FK FOREIGN KEY (MEDICINE_FK_ID)
       REFERENCES MEDICATION_MANAGER.MEDICINE (MEDICINE_ID)
);

CREATE TABLE MEDICATION_MANAGER.INVENTORY_LOG
(
    ID INT NOT NULL,
    TIME_OF_CREATION TIMESTAMP NOT NULL,
    PATIENT_FK_ID INT NOT NULL,
    MEDICINE_FK_ID INT NOT NULL,
    CHANGE_QUANTITY INT NOT NULL,
    UNITS VARCHAR(6) NOT NULL,
    REFERENCE VARCHAR(12) NOT NULL,

    CONSTRAINT INVENTORY_LOG_PK PRIMARY KEY (ID),
    CONSTRAINT INVENTORY_LOG_PATIENT_FK FOREIGN KEY (PATIENT_FK_ID)
        REFERENCES MEDICATION_MANAGER.PERSON (PERSON_ID),
    CONSTRAINT INVENTORY_LOG_MEDICINE_FK FOREIGN KEY (MEDICINE_FK_ID)
        REFERENCES MEDICATION_MANAGER.MEDICINE (MEDICINE_ID)
);

CREATE TABLE MEDICATION_MANAGER.PRESCRIPTION
(
    PRESCRIPTION_ID INT NOT NULL,
    TIME_OF_CREATION TIMESTAMP NOT NULL,
    PATIENT_FK_ID INT NOT NULL,
    PHYSICIAN_FK_ID INT NOT NULL,
    STATUS VARCHAR(10) NOT NULL,

    CONSTRAINT PRESCRIPTION_PK PRIMARY KEY (PRESCRIPTION_ID),
    CONSTRAINT PRESCRIPTION_PATIENT_FK FOREIGN KEY (PATIENT_FK_ID)
        REFERENCES MEDICATION_MANAGER.PERSON (PERSON_ID),
    CONSTRAINT PRESCRIPTION_PHYSICIAN_FK FOREIGN KEY (PHYSICIAN_FK_ID)
        REFERENCES MEDICATION_MANAGER.PERSON (PERSON_ID)
);

CREATE TABLE MEDICATION_MANAGER.TREATMENT
(
    TREATMENT_ID INT NOT NULL,
    NAME VARCHAR(77) NOT NULL,
    PATIENT_FK_ID INT NOT NULL,
    MEDICINE_FK_ID INT NOT NULL,
    PHYSICIAN_FK_ID INT NOT NULL,
    STATUS VARCHAR(10) NOT NULL,

    CONSTRAINT TREATMENT_PK PRIMARY KEY (TREATMENT_ID),
    CONSTRAINT TREATMENT_PATIENT_FK FOREIGN KEY (PATIENT_FK_ID)
        REFERENCES MEDICATION_MANAGER.PERSON (PERSON_ID),
    CONSTRAINT TREATMENT_MEDICINE_FK FOREIGN KEY (MEDICINE_FK_ID)
        REFERENCES MEDICATION_MANAGER.MEDICINE (MEDICINE_ID),
    CONSTRAINT TREATMENT_PHYSICIAN_FK FOREIGN KEY (PHYSICIAN_FK_ID)
        REFERENCES MEDICATION_MANAGER.PERSON (PERSON_ID)
);

CREATE TABLE MEDICATION_MANAGER.INTAKE
(
    ID INT NOT NULL,
    PATIENT_FK_ID INT NOT NULL,
    MEDICINE_FK_ID INT NOT NULL,
    QUANTITY INT NOT NULL,
    UNITS VARCHAR(6) NOT NULL,
    TIME_PLAN TIMESTAMP NOT NULL,
    TIME_TAKEN TIMESTAMP,
    DISPENSER_FK_ID INT,

    CONSTRAINT INTAKE_PK PRIMARY KEY (ID),
    CONSTRAINT INTAKE_PATIENT_FK FOREIGN KEY (PATIENT_FK_ID)
         REFERENCES MEDICATION_MANAGER.PERSON (PERSON_ID),
    CONSTRAINT INTAKE_MEDICINE_FK FOREIGN KEY (MEDICINE_FK_ID)
         REFERENCES MEDICATION_MANAGER.MEDICINE (MEDICINE_ID),
    CONSTRAINT DISPENSER_FK FOREIGN KEY (DISPENSER_FK_ID)
           REFERENCES MEDICATION_MANAGER.DISPENSER (DISPENESER_ID)
);

CREATE TABLE MEDICATION_MANAGER.PRESCRIBED_MEDICINE
(
    PRESCRIBED_MEDICINE_ID INT NOT NULL,
    PRESCRIPTION_FK_ID INT NOT NULL,
    MEDICINE_FK_ID INT NOT NULL,
    TREATMENT_FK_ID INT NOT NULL,

    CONSTRAINT PRESCRIBED_MEDICINE_PK PRIMARY KEY (PRESCRIBED_MEDICINE_ID),
    CONSTRAINT PRESCRIBED_MEDICINE_MEDICINE_FK FOREIGN KEY (MEDICINE_FK_ID)
        REFERENCES MEDICATION_MANAGER.MEDICINE (MEDICINE_ID),
    CONSTRAINT PRESCRIBED_MEDICINE_TREATMENT_FK FOREIGN KEY (TREATMENT_FK_ID)
        REFERENCES MEDICATION_MANAGER.TREATMENT (TREATMENT_ID)
);


  
