// PERSON TABLE

INSERT INTO MEDICATION_MANAGER.PERSON (ID, NAME, PERSON_URI, ROLE)
VALUES (1, 'Said', 'urn:org.universAAL.aal_space:test_env#saied', 'patient');

INSERT INTO MEDICATION_MANAGER.PERSON (ID, NAME, PERSON_URI, ROLE)
VALUES (2, 'd-r Pencho Penchev', 'urn:org.universAAL.aal_space:test_env#pencho', 'physician');

INSERT INTO MEDICATION_MANAGER.PERSON (ID, NAME, PERSON_URI, ROLE)
VALUES (3, 'Alejandro', 'urn:org.universAAL.aal_space:test_env#alejandro', 'patient');

INSERT INTO MEDICATION_MANAGER.PERSON (ID, NAME, PERSON_URI, ROLE)
VALUES (4, 'George', 'urn:org.universAAL.aal_space:test_env#george', 'patient');

INSERT INTO MEDICATION_MANAGER.PERSON (ID, NAME, PERSON_URI, ROLE)
VALUES (5, 'Venelin', 'urn:org.universAAL.aal_space:test_env#venelin', 'patient');

// MEDICINE TABLE

INSERT INTO MEDICATION_MANAGER.MEDICINE (ID, MEDICINE_NAME, MEDICINE_INFO, SIDE_EFFECTS, INCOMPLIANCES, MEAL_RELATION)
VALUES (1, 'Aspirin', 'Aspirin description', 'No sideeffect', 'These medications must not be used with alcohol', 'with_meal');

INSERT INTO MEDICATION_MANAGER.MEDICINE (ID, MEDICINE_NAME, MEDICINE_INFO, SIDE_EFFECTS, INCOMPLIANCES, MEAL_RELATION)
VALUES (2, 'Analgin', 'Analgin description', 'Analgin side_effects', 'Analgin incompliances', 'any');

INSERT INTO MEDICATION_MANAGER.MEDICINE (ID, MEDICINE_NAME, MEDICINE_INFO, SIDE_EFFECTS, INCOMPLIANCES, MEAL_RELATION)
VALUES (3, 'Viteral', 'Viteral description', 'Viteral side_effects', 'Viteral incompliances', 'before');

INSERT INTO MEDICATION_MANAGER.MEDICINE (ID, MEDICINE_NAME, MEDICINE_INFO, SIDE_EFFECTS, INCOMPLIANCES, MEAL_RELATION)
VALUES (4, 'Validol', 'Validol description', 'Validol side_effects', 'Validol incompliances', 'any');

INSERT INTO MEDICATION_MANAGER.MEDICINE (ID, MEDICINE_NAME, MEDICINE_INFO, SIDE_EFFECTS, INCOMPLIANCES, MEAL_RELATION)
VALUES (5, 'Benalgin', 'Benalgin description', 'Benalgin side_effects', 'Benalgin incompliances', 'after');

INSERT INTO MEDICATION_MANAGER.MEDICINE (ID, MEDICINE_NAME, MEDICINE_INFO, SIDE_EFFECTS, INCOMPLIANCES, MEAL_RELATION)
VALUES (6, 'Zocor', 'Zocor description',
'Severe allergic reactions (rash; hives; itching; difficulty breathing; tightness in the chest;swelling of the mouth, face, lips, or tongue; unusual hoarseness); burning, numbness, or tingling;change in the amount of urine produced; confusion; dark or red-colored urine; decreased sexual ability; depression; dizziness; fast or irregular heartbeat; fever, chills, or persistent sore throat; joint pain; loss of appetite; memory problems; muscle pain, tenderness, or weakness (with or without fever and fatigue); pale stools; red, swollen, blistered, or peeling skin; severe or persistent nausea or stomach or back pain; shortness of breath; trouble sleeping; unusual bruising or bleeding; unusual tiredness or weakness; vomiting;  yellowing of the skin or eyes.',
'These medications must not be used with alcohol', 'after');

// DISPENSER TABLE

INSERT INTO MEDICATION_MANAGER.DISPENSER (ID, PATIENT_FK_ID, DISPENSER_URI) VALUES (1, 1, 'dispenserUri');
INSERT INTO MEDICATION_MANAGER.DISPENSER (ID, PATIENT_FK_ID, DISPENSER_URI) VALUES (2, 4, 'dispenserUriGeorge');

// MEDICINE_INVENTORY TABLE

INSERT INTO MEDICATION_MANAGER.MEDICINE_INVENTORY (ID, PATIENT_FK_ID, MEDICINE_FK_ID, UNIT_CLASS, QUANTITY, WARNING_THRESHOLD)
VALUES (1, 1, 1, 'pills', 100, 10);

INSERT INTO MEDICATION_MANAGER.MEDICINE_INVENTORY (ID, PATIENT_FK_ID, MEDICINE_FK_ID, UNIT_CLASS, QUANTITY, WARNING_THRESHOLD)
VALUES (2, 1, 2, 'pills', 200, 10);

INSERT INTO MEDICATION_MANAGER.MEDICINE_INVENTORY (ID, PATIENT_FK_ID, MEDICINE_FK_ID, UNIT_CLASS, QUANTITY, WARNING_THRESHOLD)
VALUES (3, 1, 3, 'pills', 100, 10);

// INVENTORY_LOG TABLE

INSERT INTO MEDICATION_MANAGER.INVENTORY_LOG (ID, TIME_OF_CREATION, PATIENT_FK_ID, MEDICINE_FK_ID, CHANGE_QUANTITY, UNITS, REFERENCE)
VALUES (1, '2012-12-19 16:03:20', 1, 1, 30, 'pills', 'purchase');

INSERT INTO MEDICATION_MANAGER.INVENTORY_LOG (ID, TIME_OF_CREATION, PATIENT_FK_ID, MEDICINE_FK_ID, CHANGE_QUANTITY, UNITS, REFERENCE)
VALUES (2, '2012-12-19 16:12:24', 1, 1, -1, 'pills', 'intake');

// PRESCRIPTION TABLE

INSERT INTO MEDICATION_MANAGER.PRESCRIPTION (ID, TIME_OF_CREATION, PATIENT_FK_ID, PHYSICIAN_FK_ID, STATUS)
VALUES (1, '2012-12-19 17:07:36', 1, 2, 'y');

// TREATMENT TABLE

INSERT INTO MEDICATION_MANAGER.TREATMENT (ID, NAME, PATIENT_FK_ID, MEDICINE_FK_ID, PHYSICIAN_FK_ID, STATUS)
VALUES (1, 'holesterol', 1, 1, 2, 'y');
INSERT INTO MEDICATION_MANAGER.TREATMENT (ID, NAME, PATIENT_FK_ID, MEDICINE_FK_ID, PHYSICIAN_FK_ID, STATUS)
VALUES (2, 'holesterol', 1, 6, 2, 'y');
INSERT INTO MEDICATION_MANAGER.TREATMENT (ID, NAME, PATIENT_FK_ID, MEDICINE_FK_ID, PHYSICIAN_FK_ID, STATUS)
VALUES (3, 'cold', 1, 5, 2, 'n');
INSERT INTO MEDICATION_MANAGER.TREATMENT (ID, NAME, PATIENT_FK_ID, MEDICINE_FK_ID, PHYSICIAN_FK_ID, STATUS)
VALUES (4, 'cold', 2, 1, 2, 'y');

// INTAKE TABLE

INSERT INTO MEDICATION_MANAGER.INTAKE (ID, PATIENT_FK_ID, MEDICINE_FK_ID, QUANTITY, UNITS, TIME_PLAN)
VALUES (1, 1, 1, 1, 'pills', '2012-12-19 16:10:00');
INSERT INTO MEDICATION_MANAGER.INTAKE (ID, PATIENT_FK_ID, MEDICINE_FK_ID, QUANTITY, UNITS, TIME_PLAN)
VALUES (2, 1, 2, 2, 'pills', '2012-12-19 16:10:00');
INSERT INTO MEDICATION_MANAGER.INTAKE (ID, PATIENT_FK_ID, MEDICINE_FK_ID, QUANTITY, UNITS, TIME_PLAN)
VALUES (3, 1, 3, 3, 'pills', '2012-12-19 16:10:00');
INSERT INTO MEDICATION_MANAGER.INTAKE (ID, PATIENT_FK_ID, MEDICINE_FK_ID, QUANTITY, UNITS, TIME_PLAN)
VALUES (4, 1, 5, 2, 'pills', '2013-02-19 21:05:00');
INSERT INTO MEDICATION_MANAGER.INTAKE (ID, PATIENT_FK_ID, MEDICINE_FK_ID, QUANTITY, UNITS, TIME_PLAN)
VALUES (5, 1, 4, 1, 'pills', '2013-02-19 21:05:00');

// PRESCRIBED_MEDICINE TABLE

INSERT INTO MEDICATION_MANAGER.PRESCRIBED_MEDICINE (ID, PRESCRIPTION_FK_ID, MEDICINE_FK_ID, TREATMENT_FK_ID) VALUES (1, 1, 1, 1);
INSERT INTO MEDICATION_MANAGER.PRESCRIBED_MEDICINE (ID, PRESCRIPTION_FK_ID, MEDICINE_FK_ID, TREATMENT_FK_ID) VALUES (2, 1, 2, 1);
INSERT INTO MEDICATION_MANAGER.PRESCRIBED_MEDICINE (ID, PRESCRIPTION_FK_ID, MEDICINE_FK_ID, TREATMENT_FK_ID) VALUES (3, 1, 3, 1);



